apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ld-certificate
  namespace: linkding
spec:
  dnsNames:
    - ld-friclu.duckdns.org
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: duckdns-google-production
  renewBefore: 360h
  secretName: ld-certificate
  subject:
    organizations:
      - friclu
