apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: argo-cd
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: argo-cd
          version: 8.6.4
          repository:
            url: https://argoproj.github.io/argo-helm
