backend:
  personalName: "Fritz"
  patternFolder: "FritzSync/patterns"
  obsidianFolders:
    - "FritzSync/private"
    - "BubaFritzShare/private"
ui:
  title: "FritzGPT"
  iconPath: "icons/turtle"
  defaultModel: "gpt-5-mini"
  defaultPattern: "general"
ingress:
  host: "fritzgpt.duchardt.net"

service:
  type: ClusterIP
basicAuth:
  create: true
  secretName: "fritzgpt-basic-auth"
