oneshot:
  env:
    TELEGRAM_BOT_TOKEN: "<path:kv/data/shared/telegram#botToken>"
    TELEGRAM_CHAT_ID: "<path:kv/data/shared/telegram#chatId>"

finclaw:
  env:
    PGPASSWORD: "<path:kv/data/fritzgpt/finclaw#pgpassword>"
    POLYGON_API_KEY: "<path:kv/data/fritzgpt/finclaw#polygonApiKey>"
    TRUTHSOCIAL_TOKEN: "<path:kv/data/fritzgpt/finclaw#truthsocialToken>"
    ALPACA_API_KEY: "<path:kv/data/fritzgpt/finclaw#alpacaApiKey>"
    ALPACA_API_SECRET: "<path:kv/data/fritzgpt/finclaw#alpacaApiSecret>"
    DEEPSEEK_API_KEY: "<path:kv/data/fritzgpt/finclaw#deepseekApiKey>"
    GOOGLE_API_KEY: "<path:kv/data/fritzgpt/finclaw#googleApiKey>"
    SCRAPE_TICKER: CC.D.LCO.UNC.IP
    SCRAPE_TICKER_CURRENCY: USD
    POST_INTERPRET_PATTERN: finclaw_trump_scrape_iran
    SCRAPE_ORDER_SIZE: 0.2
    SCRAPE_ORDER_CLOSE_DELAY_SECONDS: 180
    IG_API_KEY: "<path:kv/data/fritzgpt/finclaw#igApiKey>"
    IG_USERNAME: "<path:kv/data/fritzgpt/finclaw#igUsername>"
    IG_PASSWORD: "<path:kv/data/fritzgpt/finclaw#igPassword>"
    IG_BASE_URL: "<path:kv/data/fritzgpt/finclaw#igBaseUrl>"
    X_BEARER_TOKEN: "<path:kv/data/fritzgpt/finclaw#xBearerToken>"
    TELEGRAM_CHAT_ID: "<path:kv/data/fritzgpt/finclaw#finclawTelegramChatId>"
    TELEGRAM_BOT_TOKEN: "<path:kv/data/fritzgpt/finclaw#finclawTelegramBotToken>"
    RELEVANCY_THRESHOLD: 6
    INTERPRETATION_MODEL: "gemini-3.1-flash-lite"
    RAPIDAPI_KEY: "<path:kv/data/fritzgpt/finclaw#rapidAPIKey>"
  scrapers:
    - name: parser-in-chief
      entry_cmd: 'python -m src.finclaw.cli trump scrape'
      env:
        POLL_OFFSET: 0
        LOG_LEVEL: INFO
    - name: the-best-scraper-in-the-world
      entry_cmd: 'python -m src.finclaw.cli trump scrape'
      nodeName: friclu-2
      env:
        POLL_OFFSET: 5
        LOG_LEVEL: INFO
