apiVersion: ENC[AES256_GCM,data:mn8=,iv:tTsst83GOsLgLXkKv/wymast/eUjd5JxKAtkd9GCXIg=,tag:IKr8/71ThcK67tGF8K3ESw==,type:str]
kind: ENC[AES256_GCM,data:mjrZQflp,iv:sVHJqmFI2MLXS1wbq1ZCtkKpzwcsiX2KPHx+CmNb9V8=,tag:+JWzHyrXTQJBDrkTNuFpMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Rd31LjbSFg==,iv:mP7wCsV78NDRNpubif4zNDZxGxuGDuspAkpCCQiy/WY=,tag:jq7mgQ0/jNg70hRPhedytQ==,type:str]
    namespace: ENC[AES256_GCM,data:1jVYmVUz64LI,iv:VhEYF8N256yAlHXpcWDLBR3jCKaK7ZxCreTnWV4R5SQ=,tag:sdaABXp/4eaqZDzyi+BdtA==,type:str]
type: ENC[AES256_GCM,data:sEixBASA,iv:kP8xQtAqBvif+eqoC9gZxFKmNVaY4LEeqDnWurP6rR4=,tag:Y055Zq9dIaYyY7Ct/55yKA==,type:str]
stringData:
    nextcloud-username: ENC[AES256_GCM,data:H0Aie/s=,iv:Ky0Ytgr0SK3W41meFm56IjTALJL8SiPlVmb7JvWZHss=,tag:vDzP4ldcaMKAZKSvspSBUQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:deD+bnDV5bteIFnA,iv:9bAiMBEbHNJ1uwZ7bhS/Z2Yr3sjSfCgkCmLleuU+qE4=,tag:AVONmmHIH8Auw0vlfvU5Xw==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncGxCaHkxWHpiNlBZWnBD
            SDhHTFM1b2dJcm1Fb3dJbEhMZ0dYbUpUQkJVCkZOVk5IZ3M2Z0IwRGYyVXdxQ2cy
            K1piaVBJZnpFNFJmOXpzWXBuR21zOUEKLS0tIHFZK3Rjbk1idzVPZDZkVFRzVUM4
            dHRqNVhMY3U0TUhJMEJqa3Nibk5xL0UK1kP6617Tr22hUQe/9TJrbYuAXGXk1g7y
            YbL/4igNUpmXMxFEm9MgKRymqxIiG85i7qzigNpmR3M7oh/jjlOBnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T07:19:30Z"
    mac: ENC[AES256_GCM,data:7FroLKauvFegRWRgjZ6fzkfPIRPg4de3+ttTFgdxXaEbgdRX8e790bx4FJeCAqbbkkr6P5d/RUP0OB4wrGOV5aIDiuhqyyez/2R4qyoBm26RT7o25q/XyIxuzgTSu77TpjV8IMXigujDvpXpBTRqVkuF6cLvA+BDVhYhniW20XU=,iv:TRVSAjGxkg85TbUjBBDgoriYNkHztPxK8g22gHJZCrs=,tag:ZDxDOf4X+yu93e1cWHDUwA==,type:str]
    encrypted_regex: .
    version: 3.10.2
