apiVersion: ENC[AES256_GCM,data:jTI=,iv:mPZA6vipywAW06J0qZjNHYaCZPpM21h3d5MldQbbWEM=,tag:255KdNPKS04syDBRzlVqnw==,type:str]
kind: ENC[AES256_GCM,data:ftpLyRYT,iv:YgpR8XRBvw+iSSHa5gMI9gQp6PWAnmP3Z6uKITusmOE=,tag:F11M7YKq7f2aaMnuE2onyg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7Uo6jl7Vuw==,iv:xRIuSL5WA8WpVmtecTNaSh7XmFpot7DeQbOZPZeFkC4=,tag:Tx4poh4+NK9FF5+DPSJ6Rw==,type:str]
    namespace: ENC[AES256_GCM,data:/XYtMqCBPT5E,iv:lS1ThOtyquzupzRwly3VpQ454bEX7SSRYWjEzp2/t5o=,tag:cXGaIJVp+qcuYAAYySA4dw==,type:str]
type: ENC[AES256_GCM,data:2i/YouM+,iv:6cLY18TW2iSFhaGwvn2eKx9qPNEOJCRrU7otmiwWQS4=,tag:lQ6znWK3jbaBuEIt6pyj8g==,type:str]
stringData:
    nextcloud-username: ENC[AES256_GCM,data:SRU8tmI=,iv:OF4hPwOoljh105CDXwQcSDhAvXx4ybMwXfO8YzdpoNw=,tag:HBboUCVjs6U9fRmrIYRRhw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:5Rr+DyMva2tM6JaW,iv:gk/z9/yGj5FSPqTuzKk8922QDtZnYozMtJntDeW8Ae8=,tag:7fmSqzL6L8CmeWb6a5JI8w==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeFQ1aHUxSWRUb1Vsd3JQ
            c1Y5cGwzTFZ6VGVsRWZjWjhNcTRNV1pNN1JjClNVWDYyTHYvL2NtTGJIVlMwR3ps
            QnZyclRCUkw5SlBuRHJ2TnA1YVQwcVEKLS0tIE1XMHdCbk9KRCtJVE9RZkM1MjVB
            NkZjSXNJSlBwMG40aG80S2U1ck4zbWMKnf6T1/l24XlJf4PFuDX8C+fSIKEgkusQ
            KTMgDBjO3BsXy1Pf7B0hPH9GDKW8K8OpOLSySc12SPS8YRz8xgUmHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T06:53:08Z"
    mac: ENC[AES256_GCM,data:IpjaMrxn7ylL0RsPfU5Ye34vNB2T1So8gw5XfZkj+quk+z7HrtLUZ07Es3j/NCahxtV6B1pzrZLwOLJz6B5dPfWUZLDBgcBmdK5az+5+pDJvbHbfHDz7KOippOqMTQA8yQJdIghBjPTe4YNkZJddSz97V9fZVRsJp3UElINWzbE=,iv:Lc/GeQqrYwhywCuUz1THNkjQYQ14bIFWRBYxruQGH34=,tag:DXkgTvPUCCGdNGShHoyo7g==,type:str]
    encrypted_regex: .
    version: 3.10.2
