apiVersion: ENC[AES256_GCM,data:M6E=,iv:1EuocfvSn7URan3qkAAAutNUBrhfW7mnHZA6Cvo2eTk=,tag:LzfPmxHBDdocekY2YbEAog==,type:str]
kind: ENC[AES256_GCM,data:s1el56dp,iv:Iq9UZen89nxsRvQIWKVZgHOnat3xG+knxJg8RM3Y+u4=,tag:UUT42+6pYIoSsySS1bXmgA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0KjSf0h9Vw==,iv:tiiAkpt0SNOG0VDIoQQFaFaBWgSrmSh2ynF9ovwPVr8=,tag:ab6mFucACvy9t+K+CoaA9A==,type:str]
    namespace: ENC[AES256_GCM,data:sz8Pf3mIIFOP,iv:9AEzlPPn3Zigq7LmskzJvkNUcE/juJV33ULrGwSYTsA=,tag:Ff2EDZR7FUcSno6kK4uJHw==,type:str]
type: ENC[AES256_GCM,data:5a1P2WFy,iv:BgJuIxgIYjkO9nqbSh1MZjV8uqJD+19FytgCB8nQnXA=,tag:hATFIdKYw4hqgPcLssUkww==,type:str]
stringData:
    nextcloud-username: ENC[AES256_GCM,data:AOg6w30=,iv:7JpESqin55fG3ILFmdABLGZmqnESKPidiOplqS3zTvU=,tag:wLSoimvfngyav5PTzXzxpQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:J5ls6GAyD9KLjPy9,iv:yhlMubJFw4vQAB8uMGlWNJ+nYMxA0aryj/R6VlF7ZJQ=,tag:AE+HtOo46W8dv+phI6Hfuw==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZVBFdG9MQStNcHYvLzJK
            TFNVZ1hmNmMrSm9OYXNCbjhqRWZSYUFJaHhZCkRsRzV6em9rcm9JVDd6WFQrb3Js
            ZVUxb21nMXdRcUJwb3J5ZFJXQ2swYTAKLS0tIEsvV3N5TnNjSmw0WC9xandYeW9r
            MnJIZFFubWFDUXdBVEUrUE9hYlM1UEUKgNdZGUcsEHs9TdFWq93YcR8s25dw6crH
            /vm8LiTo2BgEENKp0C0GjdjvaRomFVodYh7B0Y8ekalKjf3SGXXiBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T10:40:17Z"
    mac: ENC[AES256_GCM,data:4TntM5I+pJPbTiznkR6r8gD5hnyqOSttlehhqQRKNUIk2ksj9MGzb6+MCc3Tovct+CsHKjFATPMH5Tac+dqEiJSxXdUOabccvIy6Wb//PIa0xbC2Kcr+V1KShSlaagTD04XMonSrJDLR54CU9TwbzENLzqXzWGgbHa0dzZbMudc=,iv:G/9cpj11cbOaZXmQPvZaDIV8d9ywDAVBm74W0wc14HE=,tag:mV4si3Zfqa+i6OwvCo8tPQ==,type:str]
    encrypted_regex: .
    version: 3.10.2
