apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns-google
  name: duckdns-google:domain-solver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: duckdns-google:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
