apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cert-manager-webhook-duckdns
    chart: cert-manager-webhook-duckdns-v1.2.3
    heritage: Helm
    release: cert-manager-webhook-duckdns-github
  name: duckdns-github
  namespace: cert-manager
spec:
  replicas: null
  selector:
    matchLabels:
      app: cert-manager-webhook-duckdns
      release: cert-manager-webhook-duckdns-github
  template:
    metadata:
      labels:
        app: cert-manager-webhook-duckdns
        release: cert-manager-webhook-duckdns-github
    spec:
      containers:
        - args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --v=2
          env:
            - name: GROUP_NAME
              value: acme.friclu-github.org
          image: ebrianne/cert-manager-webhook-duckdns:v1.2.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
          name: cert-manager-webhook-duckdns
          ports:
            - containerPort: 443
              name: https
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
          resources: {}
          volumeMounts:
            - mountPath: /tls
              name: certs
              readOnly: true
      serviceAccountName: duckdns-github
      volumes:
        - name: certs
          secret:
            secretName: duckdns-github-webhook-tls
