apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
spec:
  instances: 1

  storage:
    size: 4Gi

  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: immich
        superuser: true

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
#  bootstrap:
#      postInitSQL:
#        - CREATE EXTENSION IF NOT EXISTS "vectors";
#        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
#        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
