apiVersion: ENC[AES256_GCM,data:m6U=,iv:Tr3AS7vCpZ7rMvNQ5ZOXJJu+YwfSYTvwYj67K6gXCOA=,tag:T9Exz6R+ZXXltHTVxleQOg==,type:str]
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:3Ziun5o=,iv:UphufwlVmCO6k/wOoZ1i0mQvKvTTufGpMjGKQrzVpm0=,tag:MpOlR21Pqb7MgGEpIKti+g==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:oo+G/7FDnOzuHh7q,iv:togArRJmTEbw2hT2RN/nWlFfCCxCfoTB1lMZF96tbtY=,tag:imH8bLVpT6tAym38EE5M3A==,type:str]
kind: ENC[AES256_GCM,data:kCB8MmzW,iv:hmgX30wAKlN8Qf2SNNDwUgoGb4ep1ox+/kgu9FJLJdQ=,tag:YXtQiSQuOMJ6Vas3FYn+lQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DmIwe41kKOlNl4VuJUX9,iv:ZL6w7GOiTjV18Ikdp0QMmTxApQl8yjLbCj24U8A1GRA=,tag:c0KlN8aQjfa6uXIJcSjlqg==,type:str]
    namespace: ENC[AES256_GCM,data:yLJER7fmqS8=,iv:djBsd/WSuTnFn60pN1GzlRAulRP0e987dSkvFOCORro=,tag:arsOl+/5HvvYXtr4a5GsQA==,type:str]
type: ENC[AES256_GCM,data:6DBNB3R+,iv:pfcpG07ekE5hulvhcRLg8PUcTiIv9fqx7ESFLLhZP6A=,tag:5cKq3Oxtv7tt+TXT5qexhA==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ0NLc25LVkQzSGo1Sjhu
            WDViNjdjRzBzeW1VWloxajFEU0luelBTWEZRCmdIUU5Neis0N1U2YnhINnRaTHIy
            akM3dEFZQlQraEd2WGZ4Q3YxVHhYV2sKLS0tIENaaVowL0g2aHlPTnJoeUJMbERS
            V3FqM3ZRSnNselJFMk5QOEsrUjhNVlEKE6PnAqswwmahrW5qI5l5h5zJXuRsVsuM
            hf7aqNd399wSJ+4taihCdtMgN8V1kzA50HJhui6b+wEnyPmxD/+yLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T07:41:32Z"
    mac: ENC[AES256_GCM,data:HKcaE02wc2c4R/KZTvdoHsIfc5/mo6KfPQ/oTTJzWjPnMLO9rzUU4E4uXwBWxUHyDELNvcEZOR1nKyxhUA8IK8FbO+ZnXC7EAiUl4XPR/giEpg2a2g6iGyD7xXCxcrpRxEozhSjiE2jtuu6ya3Zekaqs58UJPaP/5hNGr/bdQA4=,iv:I3UZjA/gM4WMFxp9kZKSElZmwwpVFZxait+ClReXY5A=,tag:ogu6rMuTYE9J4ZwYe6MmBQ==,type:str]
    encrypted_regex: .
    version: 3.10.2
