apiVersion: ENC[AES256_GCM,data:Ais=,iv:rKTQXEesyZQNQGGrRRO3b+FwN/nBq9LmFOCXHpzDv38=,tag:80pfdfp/UCTz4IYLhhzxcA==,type:str]
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:hl1qzck=,iv:GcnsK1kb6LpjCIwQOV8yabAP+PhyaCDtJne2tR8/mjg=,tag:aSjNkOSb4Cncu/MSAE9G2Q==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:mI9wCIewbwB4+8qX,iv:4TAqXmpIN6PlUyqquNQ2ohS6ebrsvRzMI+qxOdGy4gs=,tag:Hy6b6zXH4U71D4XzVaIqRg==,type:str]
kind: ENC[AES256_GCM,data:rGM99FEd,iv:lp92T3rr7CEa8VWJypiaNymRsaw2HMaxZWXY9Y77rfc=,tag:ImssOPjk+YBRLgeULz+kkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r0XdsCrpz+jPj9ByWUS9,iv:7s3F3qNmmPgxViPyeW5wi6aPIy5XCh1FJTuQNOtDKwg=,tag:FjcE8PlO2uXVd1wfoy3U+w==,type:str]
    namespace: ENC[AES256_GCM,data:6HDlg5EdKUk=,iv:BqEyVadLsJUBKDzQHEuRyBMcPso5zkub2spGjjwMDQg=,tag:P3x0zMkyTj0JSbC1RtYHgQ==,type:str]
type: ENC[AES256_GCM,data:B8utvO2f,iv:D4P0tC+ahUJgrBKzUBqmyanjRXbHgesF+I2TfKndANE=,tag:Yk4E/TweirBin3BIKw3nlA==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z0VNWlcvc0JNTFowWm9z
            U0dxVmZ3QXV3c3Y1UWl6dGJEbGVuLzN6YlJzClJJWEtIWWs5dVJBMm5yWTF2U3lM
            bXI3bk4vS1laM25uR2NpM0JhdzRsM2MKLS0tIE1CM2lsejlBKzFEc2xsSjFzc28r
            UlZ1UFdkVUlxbndFTlVaRXdYRVdSN1EKEHkq9FrpzGHoMDBWlhMYkgnlooJt/iDZ
            7TN1Vn/ae6Kd+SUttvLkRZj6taM1CuU2q3MAikn7taTWFJcYiB2puA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T06:53:08Z"
    mac: ENC[AES256_GCM,data:eP8nj+6q8kzObfuRT0WhymAywJUfVQRtum434nYzFTm14tDJRfwrX0C75Edu3EUZcypN1Q8X1lFkYBLRYMPa9JnbcYeYEpqqVjhArW9mgOEcYAh6n2TJ60k16xs6rPTZGcHz5mPqKw0IYrN/4x0agzgPnvvKaF16kpOeVhDs3QI=,iv:em/x6XcsVhcS4mvF4F+rMZKj9QGIbRYFXZwqWx8Ztdg=,tag:ZPnxHpiD/KSGpedDFAI8FQ==,type:str]
    encrypted_regex: .
    version: 3.10.2
