apiVersion: ENC[AES256_GCM,data:6vM=,iv:sbkmH8fn+O87iqs6PgbUexRdCSueuNzKKSQzu78Fo4c=,tag:clfZzvg/5m0Ahpzvfah3AA==,type:str]
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:QsVxY54=,iv:k9GxeZM4Q4I4Yv25VV/umzp1wtyijwRGrXKuJu0VY9A=,tag:+DaZg1Xr8wVnokR9IyJkQQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:BymRS9COXOX6iU/5,iv:srSzRpq+uvmCZSsIiQhAfUL+IjFXNAqmcYLmKcv1+kc=,tag:W3ot5YQtKCTn7Ty6kFYZDQ==,type:str]
kind: ENC[AES256_GCM,data:kuw7UF68,iv:quz4//gEH9G//jL7eSKArwEoPcLSiJ1R40EBsCLTnSc=,tag:w1FIaZPOvh6JSOnE6l7xRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ew/pDgi4rWnQPXROfl4L,iv:JY87s4GP78+UrGHKIFnYlY6V07uT9zaelw9ZCMTUzG0=,tag:yEFcgeLKzxlVUaCJUie9SQ==,type:str]
    namespace: ENC[AES256_GCM,data:tI3nqW6R6NM=,iv:sIiI4NmzTiHGXfzt5FGIwynPTA5o0Qh9IPIp+uis+m0=,tag:JbKDTJcqOPe9pxAhIERB/g==,type:str]
type: ENC[AES256_GCM,data:I3h3YTVv,iv:STd76NOW4UBasW0k1XTsJpvSywg5SA8sxh4CcXsqf/c=,tag:MmB/MdVVXrsYl3s9BHvn8g==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OHpzcU1FZlAzanJXMi9y
            dXdlUURmMFBkYnJSRVhZRTF5Rk05N3NOUWdJCjJZUGRZRCs1M3AvSXFDakdFV0JE
            djdjdmVHajYwcXhVUjVsVXcrWmhYSEkKLS0tIG8yLzYvRUprZ1JlQUg1TlRvRFRY
            czZMVzBDczQ3WmFhRjR2RzNtRURXdGsKWFtv/XPteMYwMNz8bDVhNFU6nvuYMsjo
            u3cxfoZmr69Pp7Pzc6P4VLw1NcAXRhUhdyTMcTDGSgHeadWaNGMEdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T10:40:17Z"
    mac: ENC[AES256_GCM,data:cc9WJx+dmx6Vetnz3kL45eViDm6gr5DH7aKe3yon5EM8gsruiiNKJcVcajz/j60MEdhzTMtecFlnwlOHV0TCPhQTXH07BfIKrVQp+0mQN7M8q542/wQcFhv9M8Wt5jSo6e6qHOQmTx/tZU6zMlfHar0ubUdcJgv1N4tLc74/Au0=,iv:b2QjqEPOyrE6ggq84Kg3N6lAE0wTiQxQkClUDixXM/Y=,tag:RMkOvBCnYprSzRmDIcA91A==,type:str]
    encrypted_regex: .
    version: 3.10.2
