apiVersion: ENC[AES256_GCM,data:T/g=,iv:YiTbvWB1UwfNwlswxjKfx0KUtIrnEIwkoTmfXK1WEAk=,tag:PMpA1MrGnmg6J1P4yiF23w==,type:str]
stringData:
    smtp_auth_password: ENC[AES256_GCM,data:wJkQGXmYkoPsXBKL,iv:cpiKGMKoBb8G+NGw5dNNMq5IiSW3giUYVv33r74hUiU=,tag:Y7OR9FolgTNPzKLJUl230A==,type:str]
kind: ENC[AES256_GCM,data:akF9EgYF,iv:F0DMwFuA5IRfKBIOOW6lz0UP2j3wurGNl85TCBTNmSI=,tag:ZV5YAMqM/N+XMOEqrJIzVw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hqZfoTAsHklbXMUodQTAJyc=,iv:KfvFCCkMnlz7FvTpmWO319A01wg/sMV1L3/eozCtCKI=,tag:E6NkfGJBIJu4xBS4PgyN+g==,type:str]
    namespace: ENC[AES256_GCM,data:SAroAhaswA3RPAM7r8NlZYArgNTA,iv:Xb831OfWEI0AZJix4BcjAG53Nzh6T+k0a3uF1ls1+aw=,tag:rEHselVLZN30Tcc3uttg/w==,type:str]
type: ENC[AES256_GCM,data:7N+UJWtD,iv:FfKblBHAKnMEkIoKqaJGZtzJDallDiWOgz5dLYW1VR0=,tag:h0vvYkU6E+M18ER0PEqapA==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZGZObHloT1hDK2ZWSEJp
            YmtoQmhBOFVkNmRUOFJTOGJUeFFBdUZKQ3pnCi9KVzJCNnpWTTh3cGIzRVN0d2NJ
            YVl1ajhONlhkTEZYYU9ob1EzN2hrcmMKLS0tIGViMENXL1FTZmhYMHpWbjA1UkFw
            NWVjWG1WRlh2dWphL204aGN1dmFKdXcKVCtZ7GFGDGvkLOYzXEUWGaZH1mlEFaeU
            khSZf43Q0eVcezTN6TpXTT7jM5tMazC394crb9Rld3Z+fQcsZ2yANw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T10:40:17Z"
    mac: ENC[AES256_GCM,data:ksqyDsvLY049ZP+iKEG0NNE4yBhExaWMG9nEWOV9nayWn4oB87cp5hQcDIAJkwA/AYjPsGRKeDiERxmgerQwgba6p5gvNcc2ad3+J8HisiU2NRF2zTysbqzqkyW2u42zplk/w0LNbLaL3Rp/cdnPUAfOSfduiJ3yLesKldvjyvk=,iv:5V/QmgwfswwYdc/P20zqSjs6o9PiGvKl8N2z2tCrrNY=,tag:KdbmHWZi4F7nQGFhiV5PRQ==,type:str]
    encrypted_regex: .
    version: 3.10.2
