apiVersion: ENC[AES256_GCM,data:aPs=,iv:yuJp6ewk4Hw7md0+Sk2UQaW7uAAFLCPWCBd6g7iU4M0=,tag:/6qL152YIvoPqlPpODuK9w==,type:str]
stringData:
    smtp_auth_password: ENC[AES256_GCM,data:qcOYfbS22dwZP21f,iv:t6CeC8vW1KEgAxdMqkSl8aDjqv7Tihf8K49IJ32k8z4=,tag:6yC6GEM6jvk9JykCGFeXJQ==,type:str]
kind: ENC[AES256_GCM,data:xcKR2cR5,iv:+twAgov3zWKAcE9H6KaLAgUG0vgsaa7fkxB2xDpyMdM=,tag:it/EJUHtb1cxshEYP/As1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FOt+ZHFgclv1mFNsPEpvGzY=,iv:QyuegkRNxA8dcVlS69aC3JEbyBnEKVzicD8D0UnowRY=,tag:vcZx/TOiANTT+9gaxqywjA==,type:str]
    namespace: ENC[AES256_GCM,data:63RcJHqbeWhbbIs+9n5ub7oUtjnq,iv:vRG9DyOTYdbPaBEIlK9DJ2d3CeUo7e4KKhXXq0YUhSQ=,tag:JxXqMprx0k6vDzupKNUdIg==,type:str]
type: ENC[AES256_GCM,data:vUZF8N7Q,iv:SwjR9t6OxNYfW09crC0SW1yUeHzBMHBUxpE82FHT7zM=,tag:iXSuL/jYRr2UlJ06bkXrBA==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN2pITGo5c0tqRkNaUlJn
            azQzdHVuTXVDRWxIank4RnRwcGUvcWN6bkFvCkU4T0hoU2ZWV3hkWklmT0d5Qy9u
            WEpWQlpnNUo2NVpod2F2ZkdTZk91bkEKLS0tIC9YN1NHL2N4dy8vRE5rL1ZVVUFV
            VkJ4d1M2MDRsR2R5RldoSi91REpJMU0K8l0uHXDxNlll27eXm8GAVDadgIkFAks1
            tXw1+km7lCiuonf3b3ZIgxZJY45dmSXbt07gxmwbOfccLcXbQ3N9ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T07:19:30Z"
    mac: ENC[AES256_GCM,data:ArovoN5sLcNBMQfCTlzmux/sDkQZJo5gWD2mVP6VUx6umBq8G81Xe0VTZXIpGFsss7AcTRBVb+5kQqH703okaVracGcX31iwh3ZDSjCLFsFIQ0GMzjExvkIzdMYCDTjgUDNObPLPrk8XG9TPqsaKxGGGQosfWQ4xNmCH73Aif1k=,iv:bq//D5BiSfMFUtR0W8CHbnLB5ddon+xG1sKMqu8tJQ4=,tag:0d0pT15U94zA3Yz+VtrykA==,type:str]
    encrypted_regex: .
    version: 3.10.2
