apiVersion: ENC[AES256_GCM,data:PLI=,iv:KYzPunoqNW9xyx3lpKDJ+Or9bl0uIiJbnGnlUezvQ74=,tag:uM+EZLetaC2cQ/RuelRPfg==,type:str]
stringData:
    smtp_auth_password: ENC[AES256_GCM,data:kny6czZGY1tFv0bx,iv:1UfJjatJ6NkV83oezi6JTIlsZab9XBh00EiuTR/i0oE=,tag:JdkHg3e/tpvlEdfLk3wJVg==,type:str]
kind: ENC[AES256_GCM,data:Zm5QVjuX,iv:MQsNtrBczmnbr3r0Pjkb9BgAamnB9txXRdGiB0PPANQ=,tag:FcS9KGPyXmlf5gkfP6hSpg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kx9PIWoKakTeoXqqbdc0zAo=,iv:iQyylgp9JQdyZq7s6QpM6LPHZ+Vmrh7arr61Shb6lJo=,tag:AHP7Z2S2wuuPDphSuv/2bQ==,type:str]
    namespace: ENC[AES256_GCM,data:O3X4hlJMdqAvLUHOWNgB5y7L/oWw,iv:J6MkvXEzWDq8LV4dzNiFj6Jl3XfBNRMAuERVWwBgiZI=,tag:mPuBe6fEsrB90kyhnJimig==,type:str]
type: ENC[AES256_GCM,data:PXHIvQx5,iv:l/1tDRzuHC9F+I2anSuIU1iqWA6IRMn7VoeE1S844vA=,tag:CldQOmhlAnYJDzrRYGCnAA==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRHNDQ2FsVy9peXRuU3lu
            aTN0WUJhZ0gvbklPRi9yYzduL3hML0hONlRrCmVyek1ma0d1L21mT0VpZkV0Tkxh
            R3pDVWVRUDk4T01rK2N4ZXZTNStqRTAKLS0tICt1WXF0dE00QjhxQ0NGVTdpMGdL
            aEVDUmVTSkhlMU1vYStjb2I4OVF3RjgKExygJIZ5alSerUumbK89Jhy6Fn4JCO0h
            0+8Bl86kvQ6GeaAbZ7LH8iE4sQizKqIytNIu679Um7W8SHbBR4iaVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T06:53:08Z"
    mac: ENC[AES256_GCM,data:TAsORvHP0wZKUDinjDVA3Ob3T8oHX3enLl6/PSY1G5otyxJtI7FalECEK5mno1EQ4TurR0g5irRSzURxBYyfXJ0J2wTkoHSU/YUKc1EUhEuZg6SrdTlj4K8EQUoZ6B2Z+hbueZPUD8eaofG+DVkSc3AFn8hevPUSgH1ZKDWlGOg=,iv:fWGSm9m1g0JggPt/OjZG6BwoXr6zKFppGSf0WL6OAbU=,tag:Y0Rj/X6u2YrqzvFz0zXkxg==,type:str]
    encrypted_regex: .
    version: 3.10.2
