apiVersion: ENC[AES256_GCM,data:rGw=,iv:/+1YXNRaLgA6PPEV+onwIxst6iuYBidunRFFl4dhcZE=,tag:HWcWjdsoVRyGZzk7l81Y+A==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:P2hccww=,iv:+RKjbEsGlY09B9cJnkp7qhCJJ2PrQEU1XzbWI52QEUA=,tag:11tSvGpAdlguu+PCAYf0Ww==,type:str]
    admin-password: ENC[AES256_GCM,data:7ITcfCyH51HfSFat6R+g3CRozIA=,iv:0I14cnX+MmUk293uLfFE9OxZvxckpxiOXnS/tXDcTAQ=,tag:R82a4IoFg5RDzGRFGBOocg==,type:str]
kind: ENC[AES256_GCM,data:wsZ0EPak,iv:z4m/TNgCKOiG6OOK0qB2DHp/5gzmIczwRmo+jH/86R8=,tag:GM5HuCJxFbrmux8chL1s1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tRxnxZb7OTj9Q5DFbk4=,iv:dyEq8k9EjTHnMgFAJ25oI7B0VlhzMAdLiYjbbOsttgM=,tag:e8oSSAEHK67rXxv+gulVaA==,type:str]
    namespace: ENC[AES256_GCM,data:3C4p+M6lCUDkPTxMCvPSp/m3pQpO,iv:QA5CUmYWG01SgCXAI+MzaOUaFwo1nflX+14jtN/ra4Y=,tag:gizryaKeTSae7IdUKD4OOg==,type:str]
type: ENC[AES256_GCM,data:5TsMIV5G,iv:NDFKaEAm9Ym+pkoHPOF/LEjVYOw2XDjM9Hmxms1BdnU=,tag:Ex+hdepcH9xU8LqVM6KjMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTlPc0dDYjVrbGtRenBl
            RGRiS2ozSWhGaFlvSy9USTZzRGYrd3pjZ0hFClhqdkpDSVU3SHdkY2lTWjRUalds
            c1dua0pGNVVNczZ1MU41dUwrQmpKcmcKLS0tIC9TMXFVdU1tMkRaUlZQRnZ1QXFk
            dWhDNHZsSitTWE1MTWxQc25aOVVFbGMKKLv96u/H/YSghNg+q/fXpkgUoKMkU2Bf
            JCyrHusKABjf0p4+LP0o6J8SaUIQMsH/DGRERCSKx0vDdYfMbz25OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T09:06:39Z"
    mac: ENC[AES256_GCM,data:R5N/UYAonms5OisU2SWtm/8MHZ2MqQEo0Ix2G7Ac9GYRulHk3INWbLVVL5Riz5qFO44PSrpWCNsYI3whbaFJ8R46iMQvGg+vmBk0LsBjW3gA5qvF6ttdqoxCw9mTCBk4eYCvTgb1QkYjtZNj1Sko9PsRy6WEJ1NiVhy4qKQQerI=,iv:iq9ejtc1WSnwxlHcwBFw65XeqVFvAdvVCOox3ad1BcA=,tag:KuyGb+j0yHCPS7efzr+Jxg==,type:str]
    pgp: []
    encrypted_regex: .
    version: 3.9.4
