apiVersion: ENC[AES256_GCM,data:4s4=,iv:yLYG3drjMplQvcjRyzLgm7bsfU4BurDynRO45mdJh20=,tag:WUxV9Wt7yMfA9Lw8fSRM6g==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:/4e9LiA=,iv:oPBMb0rGwRJwDWoqaL+tORDxiZdrsTWFsxOpvfevwWg=,tag:jUvvNLHgnFO6o0FdpJCG+A==,type:str]
    admin-password: ENC[AES256_GCM,data:lmm573YkS9x3SU59y0OoBYCOnPY=,iv:8j4AqMbi10SPe/YxaLBzDHkfFuFaDQD7fHOV8PQWlzA=,tag:zseXPKVc4rl6y+vX9uUjBw==,type:str]
kind: ENC[AES256_GCM,data:A9fj4XzT,iv:yi56iQH/7wSjiTkbeaOU7Plu1eV1AG4VKdP6W+ADJEA=,tag:6hIq/jdqVX4ACWqsbXjs/g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FJh+IweDN9O5Rv9wUhw=,iv:3LMe398sMerV5RR2S3VXmYh8TCdm7x32X7k0teO1l5A=,tag:STMwKdOhHXocFIWCjbmrTA==,type:str]
    namespace: ENC[AES256_GCM,data:ruZXENcanO0U3f2OL7qc6syny86O,iv:gPN8SPhvptlLWEaR7OpAx8iuXaCTPRvzZgZ3oXPaNps=,tag:KtmXcKwIFo3w0NY/SNxW0w==,type:str]
type: ENC[AES256_GCM,data:VroEbYqn,iv:Zh6zaQqr/fJ/3rEXBU6SAYI1rx1g6pqDEQBd0q/r9sk=,tag:c2/HkNkzOnwQxpUoa+hHQw==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTEw1bGFPdGFCZ2hqblBo
            T3k0T2NJT2dxUWV6ZFJmeVNFU1lnTnM5SzFFCjRJZzFLdGRhb00xNGFoaDhZbUQz
            ODNmQzM2aEprM2dmaWRpQ1VFOU5vMm8KLS0tIC9VSENUbjBBSlhYankzRHM3clN1
            MHZYSHFhUHpLODVCZ293UndEdWZ2SDAKNlyJFycDZYPP+fBQMM+ItUoccOGW64+i
            I2qpvdGJvx8bNOeeBDxZ5zgEGSCujBCGqvC26N1OoEOD23nG2pJmmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T10:40:17Z"
    mac: ENC[AES256_GCM,data:CFkgG1+OscbRzCpcdAc5oEJOEI2HXP+fHfG5nEUtLWRduKu7XjbVepFV7lts5YgIsyF66a5r9IJhV6VHq1Q/H+SCVvcgbUeIZZMhG3c8OSq6NDwyToUMGfAcmrYRJrW6sDYsU0QFTL/dkuzWOfn0C8zoAI7nWjKHpvwPff8cWHo=,iv:bU2sxlbgBCogv1+46eVNRdsIDJhqI74HvESzLhOsQhI=,tag:iWG2hCvA8hqEnckFgeWm9Q==,type:str]
    encrypted_regex: .
    version: 3.10.2
