apiVersion: ENC[AES256_GCM,data:e7w=,iv:3qr7oIjMzFIJItejLrmofFz+PbOGUJgv/xguvCnaHu8=,tag:WoXlUWy43HEEDEf+g8lwwQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:jKhYXFI=,iv:7xP8N5PdtdAavyuNudw6Vn/hNO+ILrHdQ6apEXNP4sM=,tag:o6dj8y02ywaBnYJMT15g9A==,type:str]
    admin-password: ENC[AES256_GCM,data:b8XFytqOJprMFZiXSUWgROiQCws=,iv:qXNLxujRRphUnV007KjaAZeG0gdSZOMP73qme0Bcj2c=,tag:nqrh7QLzuBv4WQx+BxawSA==,type:str]
kind: ENC[AES256_GCM,data:0iQxNIJa,iv:/r3CUQAwPKL7KnHxEhAY1qx64HJnIt+tesDvMu5JlUc=,tag:cs7k/lTNZSb9svf0Qlj4mQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Hy3WCQ+mZ4SLfdkWrMc=,iv:jmKuRHVpk+kUx0AmcbDHqwWQtm/CMhLwspK3bvzD9/c=,tag:kwM1K/fS4FFlwfzrRSK4PA==,type:str]
    namespace: ENC[AES256_GCM,data:Ezbm3Y4i8zvpt34L11Ymh6COAB1D,iv:35VBztHDMCY5Xm5li0/JK7pTdjKklslGXoLBohsIgxc=,tag:CQAxyGYRPDTaFo+iG95Ghw==,type:str]
type: ENC[AES256_GCM,data:dXC73fQr,iv:dwzb32eQ00g+keYLmfWm4/01iV1z2o/vGtnKGLQLBlc=,tag:21UzwsbolJE2K9cPVHVuQQ==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENzBEaTVKdlV1L01EYjVa
            eHdpY0FVWjk1V1A0a2Q2bVFuVGF4TkE1b2dZCnBtQmR3d2VzNGNRTWtveVFTSDhp
            QU4xbnBleG5kL1RwY1VjUUxNYXJSTU0KLS0tIG5FZnBsdi8zQkM5VjB4bDlwRmFp
            WEVsajlZQU91SnMxS1RCWFk1eWRCalUKTDhH4RgF7RPmVuzXSzlxdBxN2F3mA35g
            Ev1J8poGd7XPaAmA2rWESzFa3z5Jpra/zYLtMHO6z8CiUliof8WYqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T15:20:39Z"
    mac: ENC[AES256_GCM,data:1irYLfCPE2R61y64McX6/+DEDUvP5WrWatI62KnbsFykRONkemCL+MjSbanmhbIJBuvmcSW5p+h6TeWMgPc6HBWwCTZO7gP7Q4cVsURNtmYOAUjpid6ADKWaQSKd6IrXa4H4Ce8rEq2uy87WPlUDXdFvJYmt6whylIALNCEN5nU=,iv:N/eFXcTbnxxWt8W3g8uKRjpNX5/bOuR6AaXSWnxCmiI=,tag:2kRBUigo59ECPLDIbxwIqQ==,type:str]
    encrypted_regex: .
    version: 3.10.2
