backend:
    personalName: "Elke"
    patternFolder: "ElkeSync/patterns"
    obsidianFolders:
        - "ElkeSync/private"
        - "FritzElkeShare"
ui:
    title: "CatChat"
    iconPath: "icons/cat"
    defaultModel: "o4-mini"
    defaultPattern: "general"
ingress:
    host: catchat-friclu.duckdns.org
    tls:
        secretName: fabric-certificate
service:
    type: ClusterIP
basicAuth:
    create: false
    secretName: "catchat-basic-auth"
