apiVersion: v1
stringData:
    smtp_auth_password: <path:kv/data/alertmanager-smtp#smtp_auth_password>
kind: Secret
metadata:
    name: alertmanager-smtp
    namespace: kube-prometheus-stack
type: Opaque
