apiVersion: v1
stringData:
    admin-user: "<path:kv/data/kube-prometheus-stack/grafana-secret#admin-user>"
    admin-password: "<path:kv/data/kube-prometheus-stack/grafana-secret#admin-password>"
kind: Secret
metadata:
    name: grafana-secret
    namespace: kube-prometheus-stack
type: Opaque
