#@ load("@ytt:data", "data")
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: restic.rules
  namespace: #@ data.values.helm.namespace
spec:
  groups:
    - name: restic.rules
      rules:
        - alert: ResticBackupAbsentSyncthing
          annotations:
            description: Restic Backup absent for folder {{ $labels.dir }}
          expr: |-
            absent(restic_backup_success{dir="/volumes/syncthing"} == 0)
          for: 48h
          labels:
            severity: critical
        - alert: ResticBackupAbsentLinkding
          annotations:
            description: Restic Backup absent for folder {{ $labels.dir }}
          expr: |-
            absent(restic_backup_success{dir="/volumes/linkding"} == 0)
          for: 48h
          labels:
            severity: critical
        - alert: ResticBackupAbsentImmich
          annotations:
            description: Restic Backup absent for folder {{ $labels.dir }}
          expr: |-
            absent(restic_backup_success{dir="/volumes/immich"} == 0)
          for: 48h
          labels:
            severity: critical
        - alert: ResticBackupFailed
          annotations:
            description: Restic Backup has failed for folder {{ $labels.dir }}
          expr: |-
            restic_backup_success == 1
          labels:
            severity: critical
