storageClass:
  defaultClass: true
  defaultVolumeType: local
  name: local-path
  reclaimPolicy: Delete
nodePathMap:
- node: DEFAULT_PATH_FOR_NON_LISTED_NODES
  paths:
  - /opt/local-path-provisioner
