
---
---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-3.0.0
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: pushgateway
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
  name: pushgateway-prometheus-pushgateway
  namespace: pushgateway
automountServiceAccountToken: true
---
# Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-3.0.0
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: pushgateway
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
  name: pushgateway-prometheus-pushgateway
  namespace: pushgateway
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: pushgateway
---
# Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-3.0.0
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: pushgateway
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
  name: pushgateway-prometheus-pushgateway
  namespace: pushgateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
      app.kubernetes.io/instance: pushgateway
  template:
    metadata:
      labels:
        helm.sh/chart: prometheus-pushgateway-3.0.0
        app.kubernetes.io/name: prometheus-pushgateway
        app.kubernetes.io/instance: pushgateway
        app.kubernetes.io/version: "v1.11.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: pushgateway-prometheus-pushgateway
      automountServiceAccountToken: true
      containers:
        - name: pushgateway
          image: "quay.io/prometheus/pushgateway:v1.11.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: storage-volume
              mountPath: "/data"
              subPath: ""
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: storage-volume
          emptyDir: {}
---
# Source: prometheus-pushgateway/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-3.0.0
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: pushgateway
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
  name: pushgateway-prometheus-pushgateway
  namespace: pushgateway
spec:
  ingressClassName: nginx
  rules:
    - host: pushgateway.friclu
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: pushgateway-prometheus-pushgateway
                port:
                  number: 9091
---
# Source: prometheus-pushgateway/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-3.0.0
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: pushgateway
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
    release: kube-prometheus-stack
  name: pushgateway-prometheus-pushgateway
  namespace: kube-prometheus-stack
spec:
  endpoints:
  - port: http
    path: /metrics
    honorLabels: true
  namespaceSelector:
    matchNames:
      - pushgateway
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
      app.kubernetes.io/instance: pushgateway

---
