apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: vault
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: vault
          version: 0.31.0
          repository:
            url: https://helm.releases.hashicorp.com
