apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: weaviate
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: weaviate
          version: 17.6.0
          repository:
            url: https://weaviate.github.io/weaviate-helm
