---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/vault
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  labels:
    name: vault-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
