#@ load("@ytt:data", "data")
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n
spec:
  instances: 1
  storage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: n8n
spec:
  cluster:
    name: n8n
  name: n8n
  owner: app
