apiVersion: ENC[AES256_GCM,data:X0I=,iv:77b888o87AXqwqabWYoC6h6JpLyKULvWFXhf10S50J4=,tag:g6IDmMK6OYtvm64ImTUAAg==,type:str]
kind: ENC[AES256_GCM,data:VXzoMNV2,iv:1f1XlXWWcEqd5UaeMONYl9K/7nHuqDAtf1A9tG06TQs=,tag:TtHPWlJeN8VOqn0x79vBWw==,type:str]
type: ENC[AES256_GCM,data:44fBzTQY,iv:rba2K6h3dMBFMgmSISlmxAL3rdJaL7Gq/VvUWWaRJJw=,tag:2PmIRXBsG6+Bmy2Zgr45Pw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x7NBQNSAeEus5kkxo+b9BDGNN4mF,iv:yec6Pdfl0FQLU3rAGw59USoiUe3M2yw8RL9iVEoIT3k=,tag:Q9O8y/Xi3Pc7O3IcMY7Grw==,type:str]
    namespace: ENC[AES256_GCM,data:lcD1ofcB49CXzzMA,iv:6wshuQvoEMGtkv88vfh0g3T5tRUOAS3pDQ4vCulhPzU=,tag:QXS0N06QfX6WcXKqbEQrhw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:2tGx3uOctMMCTFywotangbJCqd+WMiMQiC4mPqkiTG5TGTqN,iv:l//MWTL8meVDzHHz1XfqrBTTigFPOLCdDLkd3fuupSg=,tag:8sVwzZWTNvAzdhbteoBvsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZEpRU00yczRrM00yQU5v
            RXJ4Ykl1MnVWRWgwQ05TQm5jNm1VaUxXUmhvCmxncmZpSVlUZVZMcWw5blkvam5j
            TG15dGdMS09xODJkanBRWlJWV0JDZEEKLS0tIDVtVjdneWs5UHZSL2NVYk1xYjh3
            aTFoODRZaXRFTXlIRlBXWTBYU3VMUDgK5ZqjrgbwJVpi5U8vEN/fhd/4FxfHramm
            RXKctaiHXaTE9jLMUqTH7qCAHsXBK2p2v3yBoE+MZUNrAjOn3EyirQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T15:15:36Z"
    mac: ENC[AES256_GCM,data:FKRuqh7s/C+krqtlQRdGudpScgZE62oX2UZLSTGuFuxzTOINUmfMW2K2YKhfIAuw8YJoGL+go2WoiUiIPKdp16QTYE6GB6mZ/BiqZ9HHl2v3XmkzCCVSriSiYd3Q4f2Oha5CkjPU6wO9NlJ9SYEMb9ycaB4BOir4xDqPE2CBDTM=,iv:pcesPSRmpn4nOJDubm5lMk8MCTTTt6uadllikEy7g5o=,tag:JVNgVoCadGZBg1Fkpxx0ug==,type:str]
    pgp: []
    encrypted_regex: .
    version: 3.9.4
