apiVersion: ENC[AES256_GCM,data:Nug=,iv:v71f8f28EuYqg67L6qwLEChIf3d0tr2GOtSi63u9vUM=,tag:xlJgt3rIDVZuTwn3GlIiSA==,type:str]
kind: ENC[AES256_GCM,data:FKKn+g6F,iv:5t6R8rM3XkPe9cnepNOJCNYWlJpAMv39g1mxgbG01ME=,tag:xhDd3uCeW5J40T+1Xjm7EQ==,type:str]
type: ENC[AES256_GCM,data:VtsW5j+y,iv:0ZoiiNezFKLQIbVkWAPpktdPzsT/EkIjQGIMXRfMBK4=,tag:2kwX3eAyzT2hqXhU4KsNcw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hqdQMTgK5HA5sMlOir3Cr6druRB8,iv:UOyz7eoupIQ6rQuWEJW7qC5oAoU+wkyCLH24r/f5QaM=,tag:4IO8eSLMnzRL2hNgz7tMAA==,type:str]
    namespace: ENC[AES256_GCM,data:DmMlNddBtam5zdId,iv:8hZRCUAQYuIXrynH7LagQIZbu+s6PKWeVRD1lzCGVVg=,tag:MI5GNZaQorTDTdZkDRW25A==,type:str]
stringData:
    token: ENC[AES256_GCM,data:OAXpLefrXz3k1VNUFg3kJHxNBwYqigISlnVjmQNacEC0LY2V,iv:OwuUAxH+RTSmgOn989ndO/5ABSOTVukShWOqUf4LG2Q=,tag:k/Imi//0lht+jAI51HZC4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM2kwanppakZpMVZGSjNU
            dzRwVGZ4SWFoQlpXbHVvb1NlQjlDaDNNcm5zCndMMm12blFtK1M0V09XZjhVMzlI
            cjZMYTMrdVgxTWd6dlRxd2RGM0FzWEEKLS0tIEJ2KzYydjdqeGdGUzIrQi9aSERU
            M1RSaktwRU1oQ0k0SWgreURVM3F1dWcKTa4J3KAzOt3Wi2QBXK2FCcbba8Wqmrih
            MZEv7Sh74v/JZRGtDcXh6HdUvdN+LHLbwcTpeYA8nYtXxqmD9X4m/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T09:06:39Z"
    mac: ENC[AES256_GCM,data:+qkdMNSFLL527A2rUEiHOMQXhp5fha7JwEiNciOAe7h+6XYEVPW5T/MNDZCDz268y9TRHMpHv9bEr0+q+2w711vGmB+55pPpJi+eKfXhSaFQ0tRVPsvv/1iVXgdxqt90/75rqBzd2UzlePHBcIxQjpyo/+WFxJS0OFBCc0FwHOM=,iv:qX6ykgYStSNAN5MDun92qUM2DybyIkRUGYYsjDdIzR8=,tag:so+AOfwdXGQet1rj6GCplQ==,type:str]
    pgp: []
    encrypted_regex: .
    version: 3.9.4
