apiVersion: ENC[AES256_GCM,data:dsg=,iv:IlHEHQEo3ZOEsFDygajovNdIkmIZsCA1cryN8XKVeyE=,tag:0rb9k1WmNK0evFuErLoVzg==,type:str]
kind: ENC[AES256_GCM,data:yt6uTS8u,iv:HeRroFdQZzIXxM8RLDRNAu7jV0IBpDbM9wpw6sSxt78=,tag:tOi+l/mowMGl7lkroa0RCA==,type:str]
type: ENC[AES256_GCM,data:8hBnyjc2,iv:LVg81EkLF/yxQQTMhRtNyYgzyaHlUOv10MKIf/BQ0Eg=,tag:ttcLptcXZi2DItctxsWoBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:V6pTn1G8CFWZhvBdmnSwWK0BxZ6p,iv:P6UMF/XBB3vaNvyyjEewCJgmUSF9DBuhDNShO/eKhQc=,tag:d+2S3vbnsyRMbXsPJ6lTnQ==,type:str]
    namespace: ENC[AES256_GCM,data:H7jLMvsdVxOfr6eM,iv:NL0DxmipWyP2y2zh9q744xE3FQ2Ev6PGPalOYVj+UfQ=,tag:/lWW1r78WEC7VDpAVinqqw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:OzVwv3CkTRXcCI7OiKNWD67/F3Whmb4/hQmElY/8uIJVxntI,iv:L7QU2E5F6kesK9FmnIWXvAc+hosIQJuplokohC4NAZs=,tag:F7cMEXjCRgZiG0WeaYA7wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYitYemhjM1l4VmVMZjBn
            K25NUzh3eFpjbHpsQXRqaVBEL2dRbkQvazNJCm1ndGRTVDZMN20vS0VGR2MrcGRh
            Q0tOb1hxeWVMWFJVVU1rV1VObjZaN00KLS0tIEhmM0pHV0J6TjJkR1c2OUQzekhw
            cXgvUGNkQWZ3Y3prY3JrMVE0QXBua2cKJ20enOy6MQ2NrYgf7z0/htuRZ9cbAw9k
            wfdkYboBaF1ZgTkyAyZ690C3HmGsz084DvYMPeuwF7zUqXpj6im7ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T06:28:25Z"
    mac: ENC[AES256_GCM,data:xht13fNr+8Hl4kHN5Aop53BpDzZVQnyOjt/JNOOrabCgmst3cGTJCsttmrUrrw5nnHy+Et6fTd+3Vwl0PDVeMBrc3q6SWc2ApA8s2X1ED2bNzILAWFCaDPml8KqU93Qhpcs25AA/IqRFJplBI3KarSqhF0tnNDUk7+r9vNY2LAc=,iv:lG/pAJZitXEEMdgrwUycyK7eP7MVAzprukXNky7iRPw=,tag:3fse6izgMZPe/3vXMIk0AA==,type:str]
    pgp: []
    encrypted_regex: .
    version: 3.8.1
