apiVersion: ENC[AES256_GCM,data:gsg=,iv:cNTsmQ//L6DCJ4jwrm2l+pHgYKJEfRt85t3dVDHRfoo=,tag:zyRcFR5l6XZFq8ajfovD1A==,type:str]
kind: ENC[AES256_GCM,data:nGVIUPxc,iv:5uJ5aZFpl1O5gAKkSS1YWy0/O8nxBUDExgrduJmgMok=,tag:TIvRaCjzD7MPX/MF0sf1VQ==,type:str]
type: ENC[AES256_GCM,data:EYBRDCNz,iv:vPEDjg80njOpfd0O/MhYyxUMnQWet/ElspNQyaVoSKw=,tag:UUHGdRxUNPPMRtq157+eVw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wbvlAHzFuED/n/8kNevTPKM2Pk1p,iv:/q0tZS9HlseMtH54pyeZeu/jBFaGx/TEyq72D00dvjU=,tag:josAI8PYlRuIoNCPOF/BzA==,type:str]
    namespace: ENC[AES256_GCM,data:hUOWxKmSD6EnrGw4,iv:Fz+UlVApSGxa7RrcHlABD3d+a5uFJhkUZc5oD431yDA=,tag:ejZhKl3nkAy0E+n5JQ63tw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:LvoK3EhbegXMqkff44UGactyxWK6GzMR+E35VvYzbrFtMhH2,iv:RxKAGUBixU54PA+x27imhMnVWCXWM3SoNzqwmuByfYo=,tag:fJUd85R58Zthf/RE/Nu/Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbmI5RTFrWWh1WlB4cCtq
            RzRCNGJHbFMyeldxWVV4SFg1MzBpOXJxYVFFCi9IRWY4VC8vV0lGN1ZkQWNETkoy
            T2lwWGJDcU5XVXRVZFhCaytHV2VSSVEKLS0tIC9tbi9CMGttcldxYjJhVmVaY3VX
            VC90aVlIMGFCWWgraUxRZWpFamRuWkkKFo7X57iTUrH7RZp+KVvxWi7yuab272zy
            UqfMDH5apzLmQl6BVJ8yzD+m2tjxk0n3goeWI4YE3s4YUqnyTkA6lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T09:06:39Z"
    mac: ENC[AES256_GCM,data:t6NALDk8Or8ZggHocmLIiOG74QsLo4NIz7vIT3EOrrjSQjV2gGMogxDXTTeKZ/xC6xE+x34bUQWMFFrkx2GFe94ECxOtPXjffK+bhXlEYOeUHR8sqKc2ddmULb3RM0QeCxY1ATqLwLnfLLylYDnamhgNzl7qE852JfjyqhQVbX4=,iv:9gY4eFPfBGEKXw6VSFX9lD+jFDE0ylW4e+6yobBRMx8=,tag:kS0FLAmfW2oGLfuBVwJyAA==,type:str]
    pgp: []
    encrypted_regex: .
    version: 3.9.4
