apiVersion: ENC[AES256_GCM,data:Lsw=,iv:UeyQoCZZEhd2BU3Rl/DaeA8SzYmyAFp+B9FMK/n8X40=,tag:xEmkavpq2O93fu69MMJajg==,type:str]
kind: ENC[AES256_GCM,data:LLYUcok4,iv:MNunJCZJrKh43PDYPFxHMJzlVuBPxGTNYuysIJPW8EY=,tag:E8u1yKA19q4x/eE4rhNWWw==,type:str]
type: ENC[AES256_GCM,data:Se6Eb8kM,iv:16nMmc5VTAqc3GricGIOQWN2CvxboObPNRE4PEwH8Ho=,tag:vEUfzs0ofzj8PHsskJ8bqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l4KEKqIJxCxbDeuIq07yjL1RRuz0,iv:2rTPV3rYfZj/e6s2maon3Ruifbf2pp7d8qfoXy/vGyQ=,tag:jcOKchzSV/KFufQMhu4TNA==,type:str]
    namespace: ENC[AES256_GCM,data:Bj54UsU/PVA7+b45,iv:2056OYaVhcZdYlg/bfdQ0q0CAmUJmb8gx4uMICavm4w=,tag:DptXTmsNqgWVBecuQYfN3g==,type:str]
stringData:
    token: ENC[AES256_GCM,data:hlarM8rwibrZCCyr18E5RAh1sqlYtz6YM61+6UeCxD27Jbhk,iv:6Fl0ge2A1fv9D+MCKiZQdTHFaqNRczGqHSTsZHVfkFI=,tag:GsVtnAj3FHMErscg5pgHqg==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeHBtdG5QNHlSLzA2Zzhh
            ekJmUFJvcUtPL0xGZjZMSnB6MmU1RlBUeTNJCld5ZURzYU1XOFE1dUNKY0tra3hF
            WHRrbGhJemIwYWdEVmI2b0Z5bW9TL3cKLS0tIFZYVkdGOE5TRWlvM0VBZXdKMDRv
            dTRaZDNvY01wVDQ5b2w3SjhOcjdhdkEKfbv6yFtJHRAlsRxy6xtA89IMuD1BlT3n
            UsvDj3wGqeTUv1JiHwBseQVwMlrcrTbzrrwUwBfxGPzGG2zZrG+kDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T07:41:32Z"
    mac: ENC[AES256_GCM,data:aFFG3g4A9zz7pv1FfP15/ISTk6KXVLQj+YU2XYwXEsApPCwX3q2+f8L/CcrjcS99PYJVDKtVyuz8guEqUAg76+2kf+hZoIzwD0Aq9DxXembzvTu6dsL+6J/xgeyPgizsLc5+CGuDA3TSGjQgDSR05ZWx1EB0B1p3t5fsaxjiWf4=,iv:CMnv7GjhnZ8qigEs30i7pl/MhXN9RTf+SF6aaoIzd3g=,tag:L917PA9bR+/POFP/6fKHqw==,type:str]
    encrypted_regex: .
    version: 3.10.2
