apiVersion: ENC[AES256_GCM,data:HPU=,iv:EmALUYckJVDGCNgLg6q3L6f2ik1RScwXoQnkrOoGyec=,tag:hfpEAHQtlGRNRuN7mpudug==,type:str]
kind: ENC[AES256_GCM,data:0KhSynJc,iv:5664jDKzqnSthpxcK5t3IQgN8DvuIyt0ztHQGDTyIQ8=,tag:JwH81pWzp9l5ly52YbqdKg==,type:str]
type: ENC[AES256_GCM,data:MEU3Ryvu,iv:x1+3w17r2anTXKmN9osE4AIAm8TW2DuzVQVdCC15nww=,tag:LjbIJKszxLjlKm2caHKS/g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nVsOsDef/9xo7UCaObvMVMoN91Ve,iv:gd1DS1ZaLhX8DWUzuGxIzcluqq0Y32KS1Hj0B7zHqsI=,tag:PXHW1S4QUXKjxsMzCaDtQA==,type:str]
    namespace: ENC[AES256_GCM,data:eCRbn5XhhNECfBh6,iv:8cpr3O5pRDzrJwjsCKKwtItr8yGHLV5DN9UJeLt+64A=,tag:nQRFvXE8bIG5Avzj6/JkNg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:IRwWJO7yh+ci3thKXlGf/wJRWhRiKXx/JOBUrbOoAEzMzAKh,iv:/VQZWo9jG+R43I3/CUJUGqoCQEQgJUPfnwe3aDGu6KQ=,tag:17PULA7jrpT0tz+YcI36YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a1ZzcXVlY1EySW84WDhP
            TmNCZlY2alpQd2JINGVwenV6cldWNDlKbVNJCktJSHVtS3RhVVhxWmZNbC9aZUdS
            T1YvYTFXeDg1SFdLdVVSVzkrdWltbEUKLS0tIFB2VmpRS01FTUxFUUZBb2ZkZ3BZ
            KzhvWUFVR2QyelZBOUVNOGJqK2wxL2sKzZCMwGFkWOLmI6LAFPL74D+GMhc1MHLE
            11MLqNquVOk8mOdAODbq3kCQGayX3WckrLNoMYL6wpkiaoeYGmnHwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T14:51:00Z"
    mac: ENC[AES256_GCM,data:dz7oZrtHFmMwygMNCFviAn7eUXAivmheGvTC+HUajbq8aDNiKDo26jm945QBTEdIUfXcNO52cXieOSepvs0tO6W3fLU46SHqnsnNGtLzBaRt41GjUGSVEoxcobTUu1SKxhkvfpGbmeNC4VR3Q+x32wznC1Vf3ijTn8tfwEiSMnY=,iv:XO9mZWs2/u3Icw9RhZkhEL2lDEjWD4ne9yLvPJL0z5U=,tag:0T8DDRtvt4dvNbtuHQIcbA==,type:str]
    pgp: []
    encrypted_regex: .
    version: 3.9.4
