apiVersion: ENC[AES256_GCM,data:2VQ=,iv:xG9Yzmqft/2S83Ir4WDHabSESvyk3Yf6t/xQgcfjNog=,tag:42SjnSmYww2MPhWT2Pea3Q==,type:str]
kind: ENC[AES256_GCM,data:sEHRjrHB,iv:te1VEmM6MDSbJLm8jIzaO5cspnAyh8ga5sm4kBCa4hI=,tag:EXCh/A6w+mMv5PdreTLLgw==,type:str]
type: ENC[AES256_GCM,data:LHsQoHS8,iv:is//WIPVBK8p5nKeK63S++fK1CXNrrNMRgd4LpqxGQo=,tag:0/2KSNQqH4H5/kq8fsb/Gw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PJdGfkdHTApix3nV7R+k8UgJ1nzi,iv:GLiY9XmqyX6fCmIvTbnDXFN5wZ2vi5sc93qdlSA71pE=,tag:HanoN+7hc38dvVx4J0WLmA==,type:str]
    namespace: ENC[AES256_GCM,data:PAXqa5xDCUSWS08H,iv:lTWQ2+t02raRoni4EIIPFBcg7Yg5B0I1oIWoRyyUKVU=,tag:yCsSyKzV3nWEmkpGHTz8xQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:UaZobT2LTiqcAbzBDLL7uepP19PZ+0Lhw/fyUCPgkrTZU2zf,iv:05M3MxrmC4jrPoCvC1T5OqR84ZYmKPNny4NXNLL0yBk=,tag:Njgc5n3IaP9C8m7z6qJuwg==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTzRBaCtNVHlxaW9DV1ZN
            QStOWTFOM3IzRmlzdElyaW9vd3VHRTc1cjNRCk4zODhGTUtkMkJBNGFNMVY3NG9a
            SnpXMUJjc1ZuWG0yZzY1Ry9EaWpENkkKLS0tIFJpWUoyZzZLeDltaTRGYnNVam5w
            NGw1NFU2THBmRnBPUiszcnlmUU41VGsKBALkMgjeeNN9zmscTJC0aOtvfRGyodce
            OWjJDcREx8/uu3at3ggZ6r1O2KPhPg9ec9ZTSRalYTdSuJIVzGdKaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T10:40:17Z"
    mac: ENC[AES256_GCM,data:frrqGez8Ju2gYa7EbfoRnwod9Y3DrlJsGUl5Fka3NeGo0vOlL1cHm5BZPpbA0hNpjr6Ko2nWYa8fYePDGLc3Ro+nMtRDZAhyRvJYT2NlPAZs5dIUizrb0YXnKChvmAcRQAFuxtW6V6gFHy6t/knR6Z2pYEZJmZOkDbUt8vurHNU=,iv:1qu7U39cWBb68vz3G5rEIvbn1+L7egmCQqgdQ/rP8SM=,tag:uvA8u0Z8PGDMgAk/IzLdmw==,type:str]
    encrypted_regex: .
    version: 3.10.2
