ingress:
  enabled: true
  className: "nginx"
  tls:
    - hosts:
        - lw-friclu.duckdns.org
      secretName: lw-certificate
  extraHosts:
    - host: lw-friclu.duckdns.org
      paths:
        - path: /
          pathType: ImplementationSpecific

linkwarden:
  nextAuthSecret:
    existingSecret:
      name: linkwarden-secret
      key: secret
  data:
    ## @param linkwarden.data.storageType [default: filesystem] The storage type to use for data, can be either 'filesystem' or 's3'
    ##
    storageType: filesystem
    ## Filesystem data settings
    ##
    filesystem:
      pvc:
        storageClass: ""
        existingClaim: "linkwarden"

nodeSelector:
  kubernetes.io/hostname: friclu-1
