#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: duckdns-github-secret
    namespace: #@ data.values.helm.namespace
stringData:
    token: "<path:kv/data/cert-manager/duckdns-github-secret#token>"
