apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: duckdns-google-secret
    # this is where cluster issuer finds them
    namespace: default
stringData:
  token: "<path:kv/data/cert-manager/duckdns-google-secret#token>"
