apiVersion: v1
kind: Secret
metadata:
  name: fabric-certificate
type: kubernetes.io/tls
stringData:
  tls.crt: "<path:kv/data/shared/wildcard-tls#tls.crt>"
  tls.key: "<path:kv/data/shared/wildcard-tls#tls.key>"
