affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - friclu-1

persistentVolumeClaim:
  existingPersistentVolumeClaim: 'linkding'
