affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - friclu-1

persistentVolumeClaim:
  existingPersistentVolumeClaim: 'linkding'

env:
  - name: LD_SUPERUSER_NAME
    valueFrom:
      secretKeyRef:
        key: LD_SUPERUSER_NAME
        name: linkding-secret
  - name: LD_SUPERUSER_PASSWORD
    valueFrom:
      secretKeyRef:
        key: LD_SUPERUSER_PASSWORD
        name: linkding-secret
