backend:
  personalName: "Isabella"
  patternFolder: "IsabellaSync/patterns"
  obsidianFolders:
    - "IsabellaSync/private"
    - "IsabellaFritzShare"
ui:
  title: "IsabellaBot"
  iconPath: "icons/racoon"
  defaultModel: "o4-mini"
  defaultPattern: "general"
ingress:
  host: isabellabot.duchardt.net
  tls:
    letsEncrypt:
      enabled: false
service:
  type: ClusterIP
basicAuth:
  create: false
  secretName: "isabellabot-basic-auth"
