backendIp: http://10.233.29.96
backend:
  personalName: "Isabella"
  patternFolder: "IsabellaSync/patterns"
  obsidianFolders:
    - "IsabellaSync/private"
ui:
  title: "IsabellaBot"
  iconPath: "icons/racoon"
  defaultModel: "gpt-5-mini"
  defaultPattern: "general"
ingress:
  host: isabellabot.duchardt.net
service:
  type: ClusterIP
basicAuth:
  create: false
  secretName: "isabellabot-basic-auth"
