server:
  dataStorage:
    enabled: false
  volumeMounts:
     - mountPath: /vault/data
       name: vault-data
  volumes:
    - name: vault-data
      persistentVolumeClaim:
        claimName: vault-data
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingressClassName: "nginx"
    hosts:
      - host: vault.duchardt.net
        paths: []
    tls:
      - secretName: vault-certificate
        hosts:
          - vault.duchardt.net
  nodeSelector:
    kubernetes.io/hostname: friclu-1
