apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: coredns
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: coredns
          version: 1.39.1
          repository:
            url: https://coredns.github.io/helm
