apiVersion: ENC[AES256_GCM,data:jDc=,iv:XmnuDohjRbL//1WLf4oXgnkwsTad57w6bNe5KGB51s0=,tag:lj7tIN6hk/WjQmrPAfpgZw==,type:str]
kind: ENC[AES256_GCM,data:jBaN5LE3,iv:himfjAflmWM7hmN2uith01wbZfVUY4FmuKWHaZ+nmD8=,tag:542yeHtWAcZp5eJjFW+hKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9upQqwZk,iv:mZ8+y2pxYPjTMyK0zmnmGBN35jzgdGpI5cLCQazGYtQ=,tag:GwsJ3yMBrRR98odwluLtLQ==,type:str]
    namespace: ENC[AES256_GCM,data:OcR1TllL,iv:3ZJdNcgzgxSt15Bph7kCXFrIKh/KAdyXQGkO6B6mZT0=,tag:tyOq1u3WWixS8ssYqhkvhQ==,type:str]
type: ENC[AES256_GCM,data:6lU5WrUe,iv:WuEdLKWSMdftxEl1sLI/wbLMxnRZ9tTGsUAWOnveCU8=,tag:8XA6h02P0+02oGU7i1Dagg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:BenIqEKmR4RMwnXL72gHtjoib1I=,iv:HOIcHFou/VN2adT4Hr9dcANJxbikp3rCbWY3ku+JTzs=,tag:aB2pDOMpvXxYKqcRSPCjfA==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTR1UEQ4ckxnUjAyL3dW
            QXdydHhYcFZNQ0h5SUZFMThwSmVPQmVPeWlvCkYzMEJDTWFCMnhJVkVBanczUWVy
            bnZVSjY1ZjVBYVlmNGk5WUIydHRHb1EKLS0tIG1CVUhVUHQ5Vm5EWkt1RjRVdk0r
            dFZSUitWWHZMaHJaYkR4djVOZnhSekkKClAlMgoYBOP2Jy6CHyiBcFXO56OjEX5D
            XxlyhRKtj80rdY6Oz2Zq7QTZWX3B8gkuuHIp2iJgKixKMXLmQnPnjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T06:44:15Z"
    mac: ENC[AES256_GCM,data:vak+KSM1I2NGzgXwau8TWiAFf9CoXkBohy+reho1b94HHScVEnm2OTjTKoxURaE9oJ1kHrO5FCsF5gfSfSACD14H1psXvSI6vyk7dWrFqX/Ko9cSW355/l1K3RB+grZblGAg+yKC4gUiyNynPr0u5h8eKyBhSfpAvoNZtAejTGg=,iv:K+6DuEyG1o6NR7AjNjtFA4YRlMLdfGLyfySD/+rA7s4=,tag:rMoJBzItt2z4dNdbrxLXKg==,type:str]
    encrypted_regex: .
    version: 3.10.2
