apiVersion: ENC[AES256_GCM,data:MtY=,iv:Vif8l9QoCb1HTvgAS+wITsQpTVek36yIPEHgASCJdLc=,tag:NUlMsKzuMZ8gsG2kk7YJXQ==,type:str]
kind: ENC[AES256_GCM,data:X4hClJP/,iv:6X9xtyVLiVVNILJ58aG1S8H6A+om38vabJmWQf0vxsI=,tag:PIfhDkPn/TFF4VrED5RRrg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Z924JrVk,iv:b1NNUaj5p0Q1KNPGsMRXKIpVTfeGoow7ssWiDGRR2Bs=,tag:voVaCqJzxvfOgsQGcHKmuQ==,type:str]
    namespace: ENC[AES256_GCM,data:UYiADEVG,iv:cPd2JGuxZK6jdeTCRz+GkYbe58AcGSfc4F1uJYup0NE=,tag:0c519TExif9qccNxnOOJYA==,type:str]
type: ENC[AES256_GCM,data:ws6UnE8S,iv:jvuiLgBTXVaRBNsGOyr1MhyhV6sCKBP/bCgb3B6GSXo=,tag:f9kjmR8ETfJaMORzq9VPCg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:Ihj37CwEnVEu1hLvkXAnrwL/SM4=,iv:jIFN8vpPqYxPtId+AyWxxTw36GN+ylMBTJgq780vVE0=,tag:EDaQVFQymseClspjXo1o8w==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeFlTUUtsUUhISHJxYlV4
            WHUyOXRiQ0x2bWpwSkY4amVwWXhQclN1a0JjCitIVk15YVdVamYxQVVBV2xoL3Uz
            YnRuTFYzbCs3MFFGeE9MWVBnb3lVWDQKLS0tIFUwSk80RFJNR3VMZSt6NnZCakgy
            U0lWWW1PMXYvSVBwNEV4K2hWYm1Zak0KgIqT7Z2Jn2wfXNeJffmR26AknhOSAE/7
            cOJ8v/AiAunD/8zm+LVv6dFyjGxVH5k1yfTbA0PZLGuafcaH/apQQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T10:40:17Z"
    mac: ENC[AES256_GCM,data:EbakFWMLEuuKgv7nwWmifioQ5HmIFk75mxOpr0WOQi36n5D+sa2J2c4Q0YHIktuW0VWeXQp4HUHVl2EERqq6Sw9rsgCEIFFpiCpTmJlbgldZylrHMJ/O5J8LfRYLCQXh/i5rxDpJogUstNTSaZv4y3ni6MCfmKPdZE7riD3RsgE=,iv:Tq5qaVeX8ciUtBaFr3AKlb02tVpKfXbtnHKG/iAxc2o=,tag:FengEhB0WfNJIp8Ku/pPxA==,type:str]
    encrypted_regex: .
    version: 3.10.2
