apiVersion: ENC[AES256_GCM,data:UHI=,iv:qm4W4j/1v6msMJkqJan1Dwb/IjW+o1o+G7XYMpe5qvQ=,tag:CcxIndcIR3mMOo0KRxawrw==,type:str]
kind: ENC[AES256_GCM,data:ZmfwmeRP,iv:AnDPRcxShRI14orRGvFeR0lZjRlvxO7Gbkv5jC4MugY=,tag:Z/J8mVwPJdLfCaSKfRLwRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hFRE9Caj,iv:QYS4X4Hejc5BT5I4PP2kwgiY7FWBBScPSvJvnakmPP4=,tag:8QZ7qnjgsHslKa9i1xggGA==,type:str]
    namespace: ENC[AES256_GCM,data:xq2nrfrZ,iv:vgjBPMIA9K8SVzgaktOHjUIviqARJBQnk5pyv9ni/3k=,tag:ZTBNNdnkCUq+1Azh6v2vkw==,type:str]
type: ENC[AES256_GCM,data:cLVdezc0,iv:rHr+4jjKjGPzf/lHzS1bcgP1fqvcJ9BbJR7U+lPiZjI=,tag:nBfej/oTOg7aJMDf2RP7JA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:XUhQZ7/qpEsLdPBC0n/5NCJP9SA=,iv:qdjjiON4qyZeFORM4znv7xb5AhPvBSNrjIpddlhHnXk=,tag:ySxU2sxUE2kZzs9jofiYdA==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UjVtQkxEc2sxeGVYZkpN
            RE52SnRqSFJtMk5tQUZqUk8vWHdnWGxuSGtzClpuYmltRkRReGt2a096Z1NzV3JJ
            UE4vdEFZKzdLeW1Ha20zMDc4ZXkyT0EKLS0tIFE3eDhzUGVTNFcvYmowMjg4dXFQ
            L3M5QXRBRHdQWDl3TkE2dGlGYk54c1EKKlNQAng7ZLfjaeQZHFTrpvEFsS+ozse9
            /7c1CPhyth1lagmpe6FXTN9gUX1URrgxQI+LmA41wX/K8IIabp42iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T07:41:32Z"
    mac: ENC[AES256_GCM,data:Vau8tCBfYbGozU7fnCeKl89HYB0X/M7fTso9CHhe8tlfDG1bjVYAg5s7yqMJNJLBSI5fzhGkp0QW/+SrnS9RZW/Lh63iDNUUWXLec162r6LMNyZnIyKgPKRGdoetdGmVGMaPkPGakklWMbex3hpmqXMJehvYvF6e6sdPJEvx7G4=,iv:C9WhQbRbqwq4WR6hou8FGJP8mK/iZDXQjXR69Hy0xoI=,tag:zQUDblY2AX1Sstjn0N2pGw==,type:str]
    encrypted_regex: .
    version: 3.10.2
