apiVersion: ENC[AES256_GCM,data:O9g=,iv:LyBNwDijkm/XLWSpAQOt52thLA42ORZ6xRKuVlqvUNM=,tag:epht4eYZv+u746bdyXHkLA==,type:str]
kind: ENC[AES256_GCM,data:WGKP7tuv,iv:TlsKfmAQrb3G45n67cvYtjb4UKXOUcotlqIHtQg9+Wk=,tag:yLbG3v86EU5qU+Pql03xYw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XhD1ASw59vQ3rPPDF+Zd78B1LA==,iv:LnbfCTTFLnXBiaqAgFGhAcJuTETn/D4p746TZ0nVY/s=,tag:SRuJ6MoEuYJ/DzHX3VDV+g==,type:str]
    namespace: ENC[AES256_GCM,data:DQn/XIGGE7Y=,iv:3ga/L55/0GreA5f5DyaI1744DIy0G2DnLcGMkeQbG8s=,tag:dn7UjmTyV+wwbwMCWMvPBg==,type:str]
type: ENC[AES256_GCM,data:L0RmFsQj,iv:snRXFUe3eJOugpWYA5BSBbcFQyV4QTEA1bhucjT+rZc=,tag:Vs35HMrSeGv0WS86y8bHDA==,type:str]
data:
    auth: ENC[AES256_GCM,data:J5rwcYDqDthvjUb9P83HNuj72yr0uXSdibtErpTs9mMnFs/gzgJKj5Z6juqmM+pfLDYiVhG9cdiwxO/K,iv:bYD8EUgD15VbYUOlc+Bz4RcSfDj71HKzX0qclHAR4Q8=,tag:DtUsFqU3Pp906EzFzdBG7A==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqazkvVEFxRnFiOHlXc1RN
            WjNSZ3c4S25UdVlXMEtpUTNNZXkwN1VCNmprCmNjTWNrV0xORlUyZ1lkRUFqNnRW
            ZDJ6a1paeUtHd09PWXlackMxZlAwK0UKLS0tIGluUFFLQmhtRXZmamJpek01YXN1
            L3VUemI5cHZ6dEdPd0dQcVlLM0tVOE0KjFGqHkiqx3ZcHFRWgTJ56o3zQzkTFQ2x
            uXo9gfvKS+G2RRXX8zYoldiWicoLHKFW+J+Sfj2SiSrhI5hHVuDY6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T07:41:32Z"
    mac: ENC[AES256_GCM,data:++lGFHYTdEiqZj9DwPall9Dm6pS6uy8XO34rjFvUqxvLZ9uVfTnCezinMYYXT7z2vMsP3s2d9dc5dUvlmhNeKiNkZFbtxCyYclLlkGFHb4epWAH1eTkdAAISz8AJAgGib8BWCCrnm2oHHGq1J16noUuP0oRpVq+6PXYebDU4bwM=,iv:qngKbomIJetW472lnJD43m0j6cZSKzeLgoM+R1DzKRI=,tag:3L+Gelzfx1EFKcbJsgR5MA==,type:str]
    encrypted_regex: .
    version: 3.10.2
