apiVersion: ENC[AES256_GCM,data:tQU=,iv:PO4dvmHyG8LKY7ZezvAONxaseNmGr50XugB5rpTKb6g=,tag:OfVuFuJKZfIornPDu2okMA==,type:str]
kind: ENC[AES256_GCM,data:jTCmuths,iv:WF2sE0KcCVBs+c8OOjLvDSCujeMxRkLlussn8tko5DE=,tag:wswWGpxi+++AeHbotCgRqA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NxclT02wnkA4m9reEyb89HIJSw==,iv:J0bCZwzuWBjHmCYxPhtX7dbjbQa/4CPUzs5YaKWbZpU=,tag:Us8/1sQCblo9aiWYQVT14Q==,type:str]
    namespace: ENC[AES256_GCM,data:gsYFRYMye5U=,iv:6Ccl4aVirgHeghB4twucvIbklDeOfLhpZGVH360DSjQ=,tag:FJ8WUXPJAbVpX7emcJZYYQ==,type:str]
type: ENC[AES256_GCM,data:mXu7KWRX,iv:9p51bQtZo0cbo33BR/0/ADilbKXQOsIiuEqQB8PzutA=,tag:+/6fkQjyhluwB1evTDfPhg==,type:str]
data:
    auth: ENC[AES256_GCM,data:8XFpDzrdMrxYUUZPF0wGLin3Ak7wsv+WSk/tBuDzmaMKb4xapKz3n3pZVPZCuroOyAu7LXEftTRZlXVn,iv:TXh1AZ/+9qeye2ynzrvZ/OvlTUmHYzfCAaKPEaaJ4X8=,tag:XN85wMFFmlgeC7vcuO1pHw==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTUYxZlNZOTBjNDkrWHBH
            OWZ5TWlZZ1lZaEtFOEtxNk81aDVjMmJ4TlFBCmtiK1RWZDZ5cVQ4YnBnZDNPVjhh
            UmJDbGlndjFpbExUWTNpaWRBZXI1MDgKLS0tIEhaV0E5V1ZkRzd5UmJMVFJPMUcy
            a1VOelJ1S2k5c0tIQmNSeVNPekhQb0UKuT/7IwRUpvrnHrs7VoovWoqNOeSH89IL
            aQyCk9lhU3gTHBCjRit8s0PXlg6eRI9El7sXKaoulsG0DlmS+LiQ2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T10:40:17Z"
    mac: ENC[AES256_GCM,data:ytbWJ4zVUUM7QtzryFo11XYeYZAr/r8jElMbs5KPfW5HVwhtZyRRNsuQsQyJkjI1IyHZwrw9yqgZV7yCDU9JsIqPcrx55GJ8WerVaWJfgbI+f+hvdWKbLbd87qAKjvS0xmWsf5oAKEdOTaqnyscoe/8N4DXmAjLNrmCdq3hj9pQ=,iv:E8Fa4tAN8tDp/c8JN6n+kLwiuq8oPJ6bQaZqLGvcJLg=,tag:kKAyweNetD92Mu54Reps7Q==,type:str]
    encrypted_regex: .
    version: 3.10.2
