#! /usr/bin/env bash
concat_yamls () {
	local file
	for file in "$1"/*; do
		if ! [[ -d "$file" ]]; then
			echo -e "---"
			cat "$file"
		fi
	done

	for file in "$1"/static/*; do
		if ! [[ -d "$file" ]]; then
			echo -e "---"
			sops -d "$file"
		fi
	done
}


apply() {
  echo "Applying Kubernetes manifests"
  local -a kapp_cmd=(kapp --yes deploy --default-label-scoping-rules=false --apply-default-update-strategy=fallback-on-replace --dangerous-override-ownership-of-existing-resources  -a "$MYKS_APP" -f -)
  concat_yamls "$MYKS_RENDERED_APP_DIR" | "${kapp_cmd[@]}"
  return $?
}

main() {
  if ! apply; then
    echo "Failed to apply manifests"
    exit 1
  fi
}

main
