affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - friclu-1

ingress:
  enabled: true
  className: nginx
  tls:
    - secretName: nc-certificate
      hosts:
        - nc-friclu.duckdns.org

nextcloud:
  host: nc-friclu.duckdns.org
  existingSecret:
    enabled: true
    secretName: nc-auth
  update: 0
  # If web server is not binding default port, you can define it
  containerPort: 80
  # if set, we'll template this list to the NEXTCLOUD_TRUSTED_DOMAINS env var
  trustedDomains: []
  extraEnv:
    - name: OVERWRITEPROTOCOL
      value: "https"
    - name: OVERWRITEHOST
      value: "nc-friclu.duckdns.org"
    - name: OVERWRITECLI_URL
      value: "https://nc-friclu.duckdns.org"

persistence:
  enabled: true
  existingClaim: nc-volume
