apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts
  contents:
  - path: gitlab
    lazy: true
    helmChart:
      name: gitlab
      version: 8.6.1
      repository:
        url: https://charts.gitlab.io/
