apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: loki
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: loki
          version: 6.45.2
          repository:
            url: https://grafana.github.io/helm-charts
