apiVersion: ENC[AES256_GCM,data:mIE=,iv:fZjFlVuNPsmQ6EUYXDecX67jPry9gWOZjrFKzDR5pGg=,tag:MpYcpJ8M56Z6HoXrnTJR0Q==,type:str]
kind: ENC[AES256_GCM,data:k709IJXg,iv:GdLLqVHEoR1vnAXj/BxSR62MqQokh8dtp2X+CBcsfhM=,tag:4+zDtbnaMD7I06YtaDlPXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lflY8AWeD/hZaVev7vSXOBaW,iv:8KtE5o6OutBPEivh+GjoDAm7sRHD0FZpNyzF6KAJRxE=,tag:zDTciM3OZ6z/jE9YOsG0XA==,type:str]
    namespace: ENC[AES256_GCM,data:lw9Nq8h8nw==,iv:7yZXoeJFt54TATrZ84rVLlfuA0F581H6eN5yl8ENrKo=,tag:mX3wRHxS1RALUnWPlyWKBQ==,type:str]
type: ENC[AES256_GCM,data:7/mv1id7,iv:7viaq9+5emOGg24sU7r9bek1bdPvDJ3lZ+Lgx6b7CcM=,tag:RO8gfUxsHmfn50rvwi7BqA==,type:str]
stringData:
    auth: ENC[AES256_GCM,data:xCwkWtfaYS12JzPPt/ucrtbAgUBjUCKYnNk5thDdbMmfvAhsEqBW5Zh7,iv:FX42uhbwCz3e6+Cl92TGUFxhZr0KilZQEReodyP7wjo=,tag:a5zKT9RIudyCNn+/2U5VfA==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNExOeG5Qc2gzMGlBVkN0
            dFBDVzY0U1llUnAxb2EzdVcvck9IeG5BQmd3CnN4U1N2WWpsQlJreXAvdy9RYzJo
            eUlLOFZwUGVGVSs5TVNwUFUxT0wxRXMKLS0tIGp6VENJbXl3ajRvRjc1MnlWV2tB
            c1FUUmxmMVIxelh2WURSREd0bnB4c2MKpqSZyHkddZNsPGUnXMh+L8VBSdyq8P1p
            hWEcRkEurnihX1ZqewrFebiPStOsRFbL4VL36uFlYYkwvlZnIaSvLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T06:53:08Z"
    mac: ENC[AES256_GCM,data:sRa2F51ozB5r9z+yP8voI6kCwEaSSQ7VRj7F8+3/lt4T0B55FuWMo1QTw5uSh/A+j7hZ6pXCGI2NEFNVvSSZGZIoSc2kP75W66U3fZcdGeeO2AKs3TN5iGqLTmf50NnF28xg6R44TMT52W9QV5FeZwiWRU7uv78dS9og1uDoPdA=,iv:9UUYENnvyUx/gcBTr5cZ49VYoWSWCMUJ7xE5p3JbCvU=,tag:noJn5H0PGR2xebcM7OCoGA==,type:str]
    encrypted_regex: .
    version: 3.10.2
