apiVersion: ENC[AES256_GCM,data:By4=,iv:sPDbzu7fEPTb7B1ZCMY81hW5N1FJ1OKvctQlpH9i4pI=,tag:CVwrNSvg6IiveQLpgfEjIQ==,type:str]
kind: ENC[AES256_GCM,data:sQkHAWnl,iv:mwhmXgnznlB+BmZ/E1vPzmC2yhpQTOg3A36+pHefYyk=,tag:/p+b3rsVxwxkCsXCGur2gg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3aMsE4rVObDiBiHkADF3xp4O,iv:bjnRO4kTq8uzCQ+rMGrEc8vE/t6Y7mm41EIuFAeBElM=,tag:KQkgXwHli74Ndm2+5tXxSQ==,type:str]
    namespace: ENC[AES256_GCM,data:1VG+g3lCRg==,iv:YEvTqzrOud1685EVWTUncwokfLmZSnRaSLJFd/vzehk=,tag:HjoW7jqfdBDjM3gRJu1bew==,type:str]
type: ENC[AES256_GCM,data:iPuPowYp,iv:uYhmhJ3nyEe/VQBKRYRITh2/0UbyXNdV7B7JqmQeVgM=,tag:CPOSHCnNa8gtfOS/omEtPw==,type:str]
stringData:
    auth: ENC[AES256_GCM,data:A5EMofhI6j742zGynwXtsob1A11JkVFRJeHjhSKgTF7lRtENzbeG2R/7,iv:OLmPERO7ZDGpxxuD2qREUP0AFwbQulBhCuqPjXACKlI=,tag:xImZZxjmlcrIkA1RiWQang==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWDduUWpqSXRvOG8vaGFO
            eWZTR2d3MjFadFZQV283dUhwVXdUTW02d1RJCmRzMXp5bllMdk5sTUoyNG5BT2JV
            Y3U5R29zQThROVZjMWV5RmY5UDVmQm8KLS0tIGJjM2pEZkdCWjVQcU56UlovQ2tu
            THl1clZvTnczelNsdkpwc3dja29CZE0KbPZFVnZb1036ptC+ggUgCVF00WWUXEs/
            PBG2gmr5Eg1GJIbnbLRF7SgmAJSElzjUGtXyOLdQLYtyjRioa2wkgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T10:40:17Z"
    mac: ENC[AES256_GCM,data:Ac/ckhbZwUVlPlwCgquzEpriyH33ds45TB+09JYG/I1QX6lL/C7ZTKvJQkJCevFboNGD3936SwiNeNOgJlvA3+3TQcG/UNq78HjWmCtjW5iW3/Hj41NJtLzEZvopwR1llVZOkpf4iZFLrIwX6Y9GBGuK7LZVP9vYJzB0tndjM3U=,iv:8Uu/ljg9o/HJPQgdjIXXWJeVSyZoOf2GiBtJ2kydCsk=,tag:mSNv/ujeW5QVgztbSVXgzA==,type:str]
    encrypted_regex: .
    version: 3.10.2
