apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: registry
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: docker-registry
          version: 2.2.3
          repository:
            url: https://helm.twun.io
