controller:
  service:
    type: NodePort
  config:
    # don't restrict body size
    proxy_body_size: 0
    # These settings don't appear to have any effect
    proxy_read_timeout: 300
    proxy_connect_timeout: 300
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  allowSnippetAnnotations: true
