kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-redundant
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  nodeSelector: "ssd"
  fsType: "ext4"
