apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: cloudnative-pg
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: cloudnative-pg
          version: 0.26.0
          repository:
            url: https://cloudnative-pg.github.io/charts
