ingress:
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
    - host: syncthing-friclu.duckdns.org
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - syncthing-friclu.duckdns.org
      secretName: syncthing-certificate
nodeSelector:
  kubernetes.io/hostname: friclu-1
persistence:
  data:
    enabled: true
    hostPath: /volumes/syncthing
    type: hostPath
