
---
---
# Source: syncthing/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: syncthing-discovery
  labels:
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/version: 1.23.5
    helm.sh/chart: syncthing-4.0.0
  annotations:
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 21027
    targetPort: 21027
    protocol: UDP
    name: discovery
  selector:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
---
# Source: syncthing/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: syncthing-listen
  labels:
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/version: 1.23.5
    helm.sh/chart: syncthing-4.0.0
  annotations:
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 22000
    targetPort: 22000
    protocol: TCP
    name: listen
  selector:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
---
# Source: syncthing/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  labels:
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/version: 1.23.5
    helm.sh/chart: syncthing-4.0.0
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8384
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/instance: syncthing
---
# Source: syncthing/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  labels:
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/version: 1.23.5
    helm.sh/chart: syncthing-4.0.0
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: syncthing
      app.kubernetes.io/instance: syncthing
  template:
    metadata:
      labels:
        app.kubernetes.io/name: syncthing
        app.kubernetes.io/instance: syncthing
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: syncthing
          image: "syncthing/syncthing:1.23.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: discovery
              containerPort: 21027
              protocol: UDP
            - name: listen
              containerPort: 22000
              protocol: TCP
            - name: http
              containerPort: 8384
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/syncthing
          livenessProbe:
            tcpSocket:
              port: 8384
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8384
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8384
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: data
          hostPath:
            path: /volumes/syncthing
      nodeSelector:
        kubernetes.io/hostname: friclu-1
---
# Source: syncthing/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing
  labels:
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/version: 1.23.5
    helm.sh/chart: syncthing-4.0.0
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "syncthing-friclu.duckdns.org"
      secretName: "syncthing-certificate"
  rules:
    - host: "syncthing-friclu.duckdns.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  number: 8384
