apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: longhorn
        lazy: true
        helmChart:
          name: longhorn
          version: 1.6.2
          repository:
            url: https://charts.longhorn.io
