apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts
  contents:
  - path: immich
    lazy: true
    helmChart:
      name: immich
      version: 0.9.0
      repository:
        url: https://immich-app.github.io/immich-charts
