apiVersion: ENC[AES256_GCM,data:5SA=,iv:KRuZx2x6QigsR/350WvF3cJfmUFnPnCkJ4heAgAcGzY=,tag:qCeT+GB2hKcBhule5PQf2g==,type:str]
kind: ENC[AES256_GCM,data:DkACBLmi,iv:TeCKdqpECmTDPrmaMedcELbHuCFm+dngymTAuJPq2O4=,tag:vmtrXGgfpvEdqBCPuCMGIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mPSyB00Ld83CFKzTrluLmfzEciTnpPg=,iv:vpTYLySYR9wUlKszgRjrbQfTE/32+Lwcv/2QOr60OpU=,tag:RCNUxtv6CiuU9qypMrlFnQ==,type:str]
    namespace: ENC[AES256_GCM,data:Ptqz7bpd5puZjh/m,iv:lWp0dfDDdxw/oy7cizgS0m05g0T6z6RoKWa9Q0IywAc=,tag:I4NW7eo4e8ViPVGw5wz6BQ==,type:str]
type: ENC[AES256_GCM,data:nJbs986B,iv:zDaENbLHx83WY/Q0og6xzAl07yE7rVhmWt2tDUR5X2Y=,tag:BEzPjlC8GQZnq6ebrp8e7w==,type:str]
stringData:
    auth: ENC[AES256_GCM,data:PdXR8qXR4b6fZ+CbaQsaIv5gHB+oCkDIDxrhMR41n4C8JnNUDZiBYl38,iv:a4H+OusCB7dYtkxrrg5J+BodJARzKQaSqE+t7R6NSsI=,tag:/FKH+Mm3QDlKQEBludiWPg==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNndGOWJDeEtUbWRNaGVU
            eWNxNHdHZ1BPbHVtc3lDMTZOUmxZSFdiclJNCmFnVGMwL2loZzdxZ1VRWEo4aEFV
            ZjFBSTZ4SFhqN28vUVZXUkw5dDdkRGcKLS0tIFpsREhpTGpkNUFySzIzL29LU0RZ
            TWF3c2kwMktIVFZta1pFeW9WZVBtRUEKDCd+XJ/CJM1bPEFi5mTX7dLTVJfrLuo9
            VXpd0rPB8OX0EnX3i7mnUg63PRYLRvjbOYjSgO3vIba8FoVodguSdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T06:44:15Z"
    mac: ENC[AES256_GCM,data:Cr+vyRznRKqRfgiFRS36nFOZ7zEgwA7SM9DuxIdZ36BWI2SW0jyRe5+28YN7tkzZAAzeJVR/dPgVgjOIOzB/JqTluNgZe9XgtpPZQXzkOwPiHcIPx2QaIt7MVqzOK14f5hGve5O3hVgZHjnh1eqVPjztBC9CZH4U/2yzUItdYlE=,iv:tf/eJmRib4F5GD7CDz3KdO3cpa4lalyjYbyRoOyIjM4=,tag:vii2K4hYDsSrbDZNTT6Ecg==,type:str]
    encrypted_regex: .
    version: 3.10.2
