apiVersion: ENC[AES256_GCM,data:CxA=,iv:nzEiTxh73ynKqpXDviotP18C8LqX73ZVzzy1HfhU9es=,tag:xboNz7YaO77sw7K5uVwhHw==,type:str]
kind: ENC[AES256_GCM,data:A2jxDYNl,iv:dGxhai+EtnwfemVqb82WSWyvLShP3T0ihNkXJ0QV35k=,tag:W9SPv8Eb6JYYnhuCtoWqlQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zcjBFNo7m46dL/O+VVu5rzFI8Ga8TJQ=,iv:q3tcYhUbk+o5oAQhT3hscIJVNcRtYXFTNAGHwPpKyt4=,tag:rwGo1wApeykGAxzQH+D7Dg==,type:str]
    namespace: ENC[AES256_GCM,data:JkOuEUiV1QozM7VD,iv:egDH9kKG4qZ1pKtxS3JNpwG5YHQXQt5rLXNzIQCc5jE=,tag:wH4g6IiU2RXo8VA/ru5Cpg==,type:str]
type: ENC[AES256_GCM,data:0t2zDotR,iv:oDqHNVO0oyd8kax9HodIOijjC/tW3TnsJbmgmrzw3mA=,tag:VfuIIiu+e3JE4VCpieqZjA==,type:str]
stringData:
    auth: ENC[AES256_GCM,data:cnrddO6NID65MBdQKj+DD1gvH+2sWDCmCBI/aOsjblUzZJyO/H+eIUm+,iv:b11cM63/Gqs/sCi3iklfzJYpxAu1BnLX28x83eAVhFs=,tag:EloVdtUvnfqmeAD+GmfIPg==,type:str]
sops:
    age:
        - recipient: age1mx6gqtque52ytw5ptc6pjnu0d06lye6tztjhhj4mjrx79qgc69tqgc4vz5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c1VtYzJOb1A4VFBmaWdm
            Z1NTQnh5cjRwQzJZTHpISTZhTG9Fblg4N2drCnFEVGpFRGEydkVhRE5xK0lRZDVr
            ZDJtR1l2Qk9jbkcrOFV6MmJtTFlYc2cKLS0tIGZSeTY4WkVhVVQyRGVlcVQ5QWtH
            UjdzOVJtbE1jMnd5UUxrVzZJZUE1SFEKuoX1xazeegmmzuWGebIvcxxml0g9UOFA
            VOakWddIKYDLm0kKysjJA5KhmnOGX6NiAObNX1L9zywWbh2yVCoXLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T06:53:08Z"
    mac: ENC[AES256_GCM,data:YnrL1zdHo3LjH/UM2aUFP/4aUzaYnvRPO+pnlUVL4rWDOe49keqp6USRYsiLak7phYsPzAH9yjWWp04ewiWxYyQZBr9puaRrthldtf5hLWULeLsi7HBxUcGL6TRR0B0Xefvxj96jotxAdY+HqJSUGklMG0aj1dp5nfIz5hn/Xxs=,iv:126B+Fz2DH3SVtLowTJJ/d1qw1dp4PKyFx6ovLhj8Fw=,tag:XM8fXH8cFFdsXbDSaOdPKw==,type:str]
    encrypted_regex: .
    version: 3.10.2
