apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: kube-prometheus-stack
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: kube-prometheus-stack
          version: 69.7.2
          repository:
            url: https://prometheus-community.github.io/helm-charts
