immich:
  persistence:
    library:
      existingClaim: immich-library

image:
  # renovate: datasource=github-releases depName="immich-app/immich"
  tag: v1.144.1

postgresql:
  enabled: true
  global:
    storageClass: local-path
  primary:
   resources:
     requests:
       cpu: 2
       memory: 512Mi
     limits:
       memory: 1024Mi

common:
  nodeSelector:
    kubernetes.io/hostname: friclu-1

redis:
  enabled: true
  global:
    storageClass: local-path
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: valkey/valkey
    tag: 8.1.3-bookworm

server:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: immich.duchardt.net
          paths:
            - path: "/"
      tls:
        - hosts:
            - immich.duchardt.net
          secretName: immich-certificate

useDeprecatedPostgresChart: true
