apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: nginx
        lazy: true
        helmChart:
          #! renovate: datasource=helm
          name: ingress-nginx
          version: 4.10.1
          repository:
            url: https://kubernetes.github.io/ingress-nginx
