backend:
  telegramBotToken: <path:kv/data/shared/telegram#botToken>
basicAuth:
  enabled: true
oauth2Proxy:
  enabled: false
  issuerUrl: "https://fricloak.duckdns.org/auth/realms/master"
  clientID: "fabric"
  clientSecret: "<path:kv/data/shared/fabric#clientSecret>"
  cookieSecret: "<path:kv/data/shared/fabric#cookieSecret>"
