apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts
  contents:
  - path: harbor
    lazy: true
    helmChart:
      name: harbor
      version: 1.14.2
      repository:
        url: https://helm.goharbor.io
