apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: coredns
            repository:
                url: https://coredns.github.io/helm
            version: 1.36.1
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-coredns-1.36.1-d2328d1d9d7e3715/data
      permissions: null
kind: Config
