apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts
  contents:
  - path: kube-prometheus-stack
    lazy: true
    helmChart:
      name: kube-prometheus-stack
      version: 69.2.0
      repository:
        url: https://prometheus-community.github.io/helm-charts
