apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: kube-prometheus-stack
            repository:
                url: https://prometheus-community.github.io/helm-charts
            version: 66.2.1
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-kube-prometheus-stack-66.2.1-521b2f841c23bdc2/data
      permissions: null
kind: Config
