alertmanager:
  enabled: true
  alertmanagerSpec:
    secrets:
    - alertmanager-smtp
    alertmanagerConfigMatcherStrategy:
      type: None
  config:
    global:
      smtp_smarthost: 'smtp.easyname.com:465'
      smtp_from: 'fritz@duchardt.net'
      smtp_require_tls: false
      smtp_auth_username: 'fritz@duchardt.net'
      smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-smtp/smtp_auth_password

grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Tempo2
        type: tempo
        uid: tempo
        url: http://tempo.tempo:3200
        access: proxy
        basicAuth: false
        jsonData:
          httpMethod: POST
          timeInterval: 30s
          tracesToLogs:
            datasourceUid: 'loki'
            tags: [{key: 'namespace'}]
            spanStartTimeShift: '-10ms'
            spanEndTimeShift: '10ms'
      - name: Loki
        type: loki
        uid: loki
        url: http://loki.loki:3100
        access: proxy
        basicAuth: false
        jsonData:
          httpMethod: POST
          timeInterval: 30s
  assertNoLeakedSecrets: false
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - grafana.duchardt.net
    tls:
     - secretName: grafana-certificate
       hosts:
        - grafana.duchardt.net
  admin:
    existingSecret: grafana-secret
  persistence:
    enabled: true
  sidecar:
    datasources:
      url: http://prometheus-operated:9090/
      alertmanager:
        enabled: false
  grafana.ini:
    server:
      root_url: https://grafana.duchardt.net
    auth.generic_oauth:
      enabled: true
      name: Keycloak-OAuth
      allow_sign_up: true
      client_id: grafana
      client_secret: '<path:kv/data/kube-prometheus-stack/grafana-client-secret#secret>'
      scopes: "openid email profile offline_access roles"
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: https://keycloak.duchardt.net/auth/realms/master/protocol/openid-connect/auth
      token_url: https://keycloak.duchardt.net/auth/realms/master/protocol/openid-connect/token
      api_url: https://keycloak.duchardt.net/auth/realms/master/protocol/openid-connect/userinfo
      role_attribute_path: "contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'"
      allow_assign_grafana_admin: true
prometheus:
  ingress:
    ingressClassName: "nginx"
    enabled: false
    hosts:
      - prometheus.friclu
  prometheusSpec:
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}

defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: false
    configReloaders: false
    general: true
    k8sContainerCpuUsageSecondsTotal: false
    k8sContainerMemoryCache: false
    k8sContainerMemoryRss: false
    k8sContainerMemorySwap: false
    k8sContainerResource: false
    k8sContainerMemoryWorkingSetBytes: false
    k8sPodOwner: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubelet: false
    kubeProxy: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: false
    network: false
    node: false
    nodeExporterAlerting: false
    nodeExporterRecording: false
    prometheus: false
    prometheusOperator: false
    windows: false
