## For creating the StorageClass automatically:
storageClass:
  defaultClass: true
  ## The default volume type this storage class creates, can be "local" or "hostPath"
  defaultVolumeType: local
  ## Set a StorageClass name
  ## Ignored if storageClass.create is false
  name: local-path
  ## ReclaimPolicy field of the class, which can be either Delete or Retain
  reclaimPolicy: Delete

# The configuration must obey following rules:
# 1. A path must start with /, a.k.a an absolute path.
# 2. Root directory (/) is prohibited.
# 3. No duplicate paths allowed for one node.
# 4. No duplicate node allowed.
nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /opt/local-path-provisioner
