apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/version: 1.23.5
    helm.sh/chart: syncthing-4.0.0
  name: syncthing
  namespace: syncthing
spec:
  ports:
    - name: http
      port: 8384
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: syncthing
    app.kubernetes.io/name: syncthing
  type: ClusterIP
