---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkwarden
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/linkwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden
  labels:
    name: linkwarden
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
