apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: vaultwarden
        lazy: true
        helmChart:
          name: vaultwarden
          version: 0.31.2
          repository:
            url: https://guerzon.github.io/vaultwarden
