apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: home-assistant
        lazy: true
        helmChart:
          # renovate: datasource=helm
          name: home-assistant
          version: 0.2.110
          repository:
            url: http://pajikos.github.io/home-assistant-helm-chart/
