apiVersion: v1
stringData:
    LD_SUPERUSER_NAME: "<path:kv/data/linkding/linkding-secret#LD_SUPERUSER_NAME>"
    LD_SUPERUSER_PASSWORD: "<path:kv/data/linkding/linkding-secret#LD_SUPERUSER_PASSWORD>"
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
