---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkding
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /volumes/linkding
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding
  labels:
    name: linkding
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
