apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
type: Opaque
stringData:
  VAULT_ADDR: "http://vault.vault:8200"
  AVP_AUTH_TYPE: "token"
  # Read only, all public repos
  VAULT_TOKEN: "<path:kv/data/argocd/avp#vault-token>"
  AVP_TYPE: "vault"
