apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
type: Opaque
stringData:
  VAULT_ADDR: "http://vault.vault:8200"
  AVP_AUTH_TYPE: "github"
  # Read only, all public repos
  AVP_GITHUB_TOKEN: "<path:kv/data/argocd/avp#github-token>"
  AVP_TYPE: "vault"
