apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: friclu
  namespace: argoapps
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - 'argoapps'
