backend:
  personalName: "Buba"
  patternFolder: "BubaSync/patterns"
  obsidianFolders:
    - "BubaSync/private"
    - "BubaFritzShare"
ui:
  title: "MunchkinChat"
  iconPath: "icons/munchkin"
  defaultModel: "o4-mini"
  defaultPattern: "journal"
ingress:
  host: munchkinchat-friclu.duckdns.org
  tls:
    secretName: fabric-certificate
service:
  type: ClusterIP
basicAuth:
  create: false
  secretName: "munchkinchat-basic-auth"
