backend:
  personalName: "Buba"
  patternFolder: "BubaSync/patterns"
  obsidianFolders:
    - "BubaSync/private"
    - "BubaFritzShare"
ui:
  title: "MunchkinChat"
  iconPath: "icons/munchkin"
  defaultModel: "claude-opus-4-20250514"
  defaultPattern: "journal"
ingress:
  host: munchkinchat-friclu.duckdns.org
  tls:
    secretName: fabric-certificate
service:
  type: ClusterIP
basicAuth:
  create: false
  secretName: "munchkinchat-basic-auth"
